### ISSUE TITLE
vod.pl / brak aktywnosci w kategoriach

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#10]
hej,

https://vod.pl/polskie-komedie-romantyczne/pech-to-nie-grzech-caly-film-online/hch8sm9

kategoria /polskie-komedie-romantyczne/ - zakładam ze to tego wina.

skrypt się nie aktywuje.... dajmy na to taki adres: https://vod.pl/filmy/przytul-mnie-online/k12bk9m

tutaj juz działa.

idac dalej: https://vod.pl/komedie/irlandzki-numer/4de31qg
tu rownież nie działa.

to samo dla filmow 'polskie-komedie' 

próbowałem zrobić:
// @include        /^https://vod.pl/(komedie|polskie-komedie|polskie-komedie-romantyczne|filmy|programy-onetu|da-vinci|seriale|programy-tv)/.*

ale nie reaguje na taka zmianę... dodatkowo gdy podmieniam własnie na to wyzej
to wtedy tez juz nie reaguje nawet na: https://vod.pl/filmy/przytul-mnie-online/k12bk9m 

edit.
dobra, moja nieuwaga, wszystko działa, gdy zamienimy:

`        {action: VOD.waitOnWrapper, pattern: new RegExp('^https:\/\/vod.pl\/(filmy|programy-onetu|da-vinci|seriale|programy-tv)\/.*')},`

na

`
{action: VOD.waitOnWrapper, pattern: new RegExp('^https:\/\/vod.pl\/(komedie|polskie-komedie|polskie-komedie-romantyczne|filmy|programy-onetu|da-vinci|seriale|programy-tv)\/.*')},`

i 

`// @include        /^https://vod.pl/(komedie|polskie-komedie|filmy|programy-onetu|da-vinci|seriale|programy-tv)/.*`

na
`
// @include        /^https://vod.pl/(komedie|polskie-komedie|polskie-komedie-romantyczne|filmy|programy-onetu|da-vinci|seriale|programy-tv)/.*`

chyba ze sa jescze jakies dodatkowe 'kategorie' nie uwzględnione w skrypcie

pozdrawiam.

edit2.
kolejna kategoria:
* bajki-dla-dzieci-po-polsku
* filmy-romantyczne
* polskie-filmy
* filmy-i-bajki-dla-dzieci
* polskie-filmy-na-majowke-taniej
* filmy-z-dubbingiem

**Comment by HerMajestyDrMona** [comment]
Na razie włączmy to na wszystkich podstronach vod.pl.
https://github.com/zacny/voddownloader/commit/3b8c22028050e43531f0b9d98a028049bb1b4955
https://github.com/zacny/voddownloader/commit/c42c02adddf786b2fb86662ae9f61658e92919d4

Chyba nie ma jakichś przeciwwskazań, a dzięki temu działa na wszystkich podstronach, bez potrzeby listowania kategorii.
