### ISSUE TITLE
cda.pl wtyczka nie działa

### ISSUE THREAD

**Issue by morarz** [zacny/voddownloader#106]
Otwiera się nowe okno w przeglądarce, klikam pobierz video i pisze tylko:
Rozpoczęto pobieranie pliku
22:02:26
×
Skazany na bluesa (2005) Cały film PL 720p

I nic się nie dzieje, naprawicie to ?

**Comment by jarox69x** [comment]
Od kilku dni nie działa wtyczka na CDA i VOD.TVP
Ikonka się pojawia, po jej naciśnięciu wyskakują pliki do pobrania - niestety po wybraniu pliku, co prawda pojawia się informacja - "rozpoczęto pobieranie pliku", ale zaraz potem jest informacja, że pobranie nie powiodło się. Próbowałem na dwóch przeglądarkach: Chrome i Firefox oraz sprawdzałem 2 wersje skryptu 7.2.4 i 7.2.7 - nic nie działa.
Z góry dziękuję za pomoc.

**Comment by zerr11** [comment]
same cda.pl not working, i nothing see new mozilla  97.0.2 can fix this why stop working.

**Comment by zacny** [comment]
Firefox 100.0.2 everything works fine.
