### ISSUE TITLE
TVP zmienila kilka dni temu skrypt wyswieltlania filmow i voddownloader juz nie dziala

### ISSUE THREAD

**Issue by batiar1** [zacny/voddownloader#107]
TVP zmienila kilka dni temu skrypt wyswieltlania wszystkich filmow i voddownloader juz nie dziala. Pilnie potrzebna jest aktualizacja skryptu voddownloadera dla vod.tvp.pl, cyfrowa.tvp.pl itp.

**Comment by zacny** [comment]
Przykładowy url poproszę.

**Comment by batiar1** [comment]
Pzzyklad:
:
https://vod.tvp.pl/video/przystan,przystan,37548610

**Comment by zacny** [comment]
wersja 7.2.4 działa bez problemu

**Comment by batiar1** [comment]
Uaktualnilem wersje i faktycznie dziala.
