### ISSUE TITLE
Nie moge zapisac zmian w ustawieniach w Przegladanie BETA

### ISSUE THREAD

**Issue by RawFedFerrets** [zacny/voddownloader#111]
Witam, mam problem ze zmiana ustawien w Przegladanie BETA, kiedy wbieram Przegladarki API i klikne Zapisz nic sie nie dzieje. Mialam ten sam problem kozystajac ze starego jak i z nowego poradnika.

**Comment by RawFedFerrets** [comment]
Ok, no wiec mialam problem z Chrome i Firefox ale w Operze sie udalo! Jednak i tak brakuje ikonki zapisania w playerze :(

**Comment by batiar1** [comment]
Ja mam tez sam problem z Chrome. Wersja 7.2.7 ma blad bo gdy sie instaluje to Przegladanie BETA nie zapisuje sie jako  API Przegladarki tylko jako Default, a gdy sie wybierze API Przegladarki to nie mozna zapisac tego ustawienia.

Dawna wersja chyba 7.2.4 nie miala tego problemu.

**Comment by batiar1** [comment]
Dzisiaj Tampermonkey uaktualnil sie do wersji 4.16 i udalo sie zapisac dla Chrome w ustawieniach Voddownloadera API Przegladarki.

**Comment by zacny** [comment]
Nie był to błąd skryptu. Problem po stronie pluginu.
