### ISSUE TITLE
Nie działa mi voddownloader

### ISSUE THREAD

**Issue by BOSTON04** [zacny/voddownloader#114]
Nie pojawia się ikonka tej kamerki który przenosiła na stronę do pobierania.
Proszę o pomoc

**Comment by hj1978** [comment]
Potwierdzam że TVP VOD nie działa od wczoraj (22.05.17).

**Comment by zacny** [comment]
Tak witryna przeszła jakieś gruntowne zmiany. Zmian jest naprawdę sporo. Dostosowanie skryptu do zmian, może nieco potrwać. Mam nadzieję, że zmiany nie są na tyle szeroko zakrojone, że wypracowane podejście do pobierania materiałów przestanie mieć zastosowanie. Widzę, że na razie mam problem nawet z samym obejrzeniem materiałów obecnie. Mimo wyłączenia wtycznik blokującej reklamy. Wygląda jakby były jeszcze jakieś błędy po ostatnich zmianach, więc nie wiem czy nie będę musiał odczekać jakiś czas na poprawę takich rzeczy zanim rozpocznę przeróbki skryptu.

**Comment by robak29** [comment]
Zgadza się, najważniejsze że dalej przez api - da się dostać do linków :

https://vod.tvp.pl/sess/TVPlayer2/api.php?id=60029569&@method=getTvpConfig&@callback=callback

**Comment by BOSTON04** [comment]
> Zgadza się, najważniejsze że dalej przez api - da się dostać do linków :
> 
> https://vod.tvp.pl/sess/TVPlayer2/api.php?id=60029569&@method=getTvpConfig&@callback=callback

Jak wyciągnąć takie api sobie?

**Comment by kosiarz66** [comment]
> Zgadza się, najważniejsze że dalej przez api - da się dostać do linków :
> 
> https://vod.tvp.pl/sess/TVPlayer2/api.php?id=60029569&@method=getTvpConfig&@callback=callback

nie działa na tampermoneky pokazuje zły script.
Jak zrobić by poprawnie działało i dało się pobierać z voda mimo wszystko

**Comment by robak29** [comment]
> > Zgadza się, najważniejsze że dalej przez api - da się dostać do linków :
> > https://vod.tvp.pl/sess/TVPlayer2/api.php?id=60029569&@method=getTvpConfig&@callback=callback
> 
> nie działa na tampermoneky pokazuje zły script. Jak zrobić by poprawnie działało i dało się pobierać z voda mimo wszystko

To nie skrypt - tylko czysty link do api - podmieniasz ID materiału na ten który chcesz pobrać i wczytujesz wteddy link w pasku u góry w przeglądarce

**Comment by elelek** [comment]
Ja od siebie dodam, bo może to się okaże POMOCNE dla ZACNY (choć pewnie już o tym wie):
a) na tvpsport vod ten skrypt dalej działa
b) ten skrypt działa https://greasyfork.org/en/scripts/18671-inject2download - pokazuje się jeden link, który dodajemy np. do jdownloader i pokazują się wszystkie możliwe rozdziałki do pobrania
c) IDM też oczywiście działa

Tak jak napisałem, to tylko jako "pomoc" dla ZACNY, bo czekam z niecierpliwością aż naprawi skrypt :)

**Comment by zacny** [comment]
Powinno być ok.

**Comment by X3nuPL** [comment]
@zacny i nadal nie jest na TVP VOD.
