### ISSUE TITLE
Nazwy plików

### ISSUE THREAD

**Issue by elelek** [zacny/voddownloader#115]
Pytanko pod tvpvod: a czy ZACNY dałby radę zrobić/poprawić w tym skrypcie, aby to co pobieramy przez niego na dysk było podpisane tak jak to tytułuje tvpvod?
Dla przykładu pobierając z tvpvod poprzez FireDM wszystko mamy od razu poprawnie podpisane.

Tak, wiem, że trzeba się cieszyć, że w ogóle Twój skrypt działa i chce Ci się, ale... no fajnie by było gdyby skrypcik od razu podpisywał pobrane pozycje :)

**Comment by zacny** [comment]
Nie wiem w czym problem. Proszę o konkrenty przykład.

**Comment by elelek** [comment]
Tu nie chodzi o problem, a bardziej o udogodnienie.
Po prostu fajnie by było gdybym pobierając np. to https://vod.tvp.pl/video/pitbull,odc-1,29702 otrzymał plik na dysku podpisany zgodnie z tvpvod czyli "Pitbull odc. 1", a nie tak jak to teraz jest "video-9".

**Comment by zacny** [comment]
Tytuł zapiszę się taki jak oczekujesz, jeżeli użyjesz przycisku pobierz, a nie kopiuj.

**Comment by elelek** [comment]
Aaaa, OK to już wszystko jasne. Ja pobieram przez jdnownloader , więc muszę kopiować. OK, teraz już wszystko rozumiem.
