### ISSUE TITLE
skrypt 7.3.1 - tvpvod nie działa

### ISSUE THREAD

**Issue by elelek** [zacny/voddownloader#116]
Tak jak w temacie:
Pierwsze czego nie mogę pobrać to np.: https://vod.tvp.pl/video/pitbull,odc-24,60980

Błąd:
Niestety natrafiono na problem, który uniemożliwił dalsze działanie
Nie udało się odnaleźć idetyfikatora.
Algorytm rozpoznawania identyfikatora wideo na stronie: https://vod.tvp.pl/video/pitbull,odc-24,60980 zakończył się niepowodzeniem. Może to oznaczać błąd skryptu lub zmiany w portalu.
Informacje o systemie: Chrome 100.0.4896.162 on Windows 10 64-bit
Wersja pluginu: 4.16.1
Wersja skryptu: 7.3.1

**Comment by robak29** [comment]
Tak, ogólnie to czemu skrypt na greasyfork.org nie jest aktualizowany ?

**Comment by zacny** [comment]
Bo, tak są blokowane skrypty, które dociągają zasoby z zewnątrz.

**Comment by zacny** [comment]
Poprawione.
