### ISSUE TITLE
brak komunikatu błędu

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#12]
dla materiału:
https://vod.pl/filmy/moj-piekny-syn-caly-film-online/4s9195g

zamiast konkretnej wiadomości zwrotnej, mówiącej o tym, ze nie można wyswetlic linków bo...

wyświetla sie pusta strona z tytułem.

**Comment by funplayertv** [comment]
@zacny dodatkowo, dla materiału: https://player.pl/seriale-online/pod-powierzchnia-odcinki,14889

wyświetla sie pusta strona - nawet  bez tytułu... 

ale juz dla https://player.pl/seriale-online/pod-powierzchnia-odcinki,13621 działa bezproblemu...

różnice widac po wejsciu na dany materiał... a podpowiem... chodzi o rozdzielczość.... :) 

obydwa linki prowadza do tego samego serialu, z rożnica, ze jeden jest w innej rozdzielczosci, 

zakładam ze nie da rady wyciagac az takiej, co?

**Comment by HerMajestyDrMona** [comment]
Hmmm, tradycyjnie, stara wersja "4.9" wyciąga dla: 
https://player.pl/seriale-online/pod-powierzchnia-odcinki,14889

Dla: https://vod.pl/filmy/moj-piekny-syn-caly-film-online/4s9195g
Wyświetla komunikat o DRM.

Będzie trzeba sprawdzić czy wykorzystywana jest ta sama metoda czy inna.

**Comment by sebekhtc** [comment]
https://player.pl/big-brother/big-brother-odcinki,17822/odcinek-74,S01E74,145503
tez nie dziala

**Comment by sebekhtc** [comment]
https://player.pl/big-brother/big-brother-odcinki,17822/odcinek-74,S01E74,145503
tez nie dziala

EDIT: już działa

**Comment by zacny** [comment]
https://player.pl/seriale-online/pod-powierzchnia-odcinki,14889
To jakiś błąd api. Json ma tylko jedno pole.
