### ISSUE TITLE
Player - pusta strona

### ISSUE THREAD

**Issue by fokafoto** [zacny/voddownloader#14]
https://player.pl/big-brother/big-brother-arena-odcinki,17810/odcinek-13,S01E13,142074
https://player.pl/programy-online/w-dobrym-stylu-odcinki,4667/odcinek-8,S03E08,82113
po kliknięciu "pobierz video" wyświetla się pusta strona

**Comment by HerMajestyDrMona** [comment]
https://github.com/zacny/voddownloader/issues/12
