### ISSUE TITLE
brak mozliwosci pobierania

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#15]
pomimo zmiany ustawień wtyczki, na ustawienia pobierania API - aby w ogole przycisk pobierania był aktywny, resecie przeglądarki itd. po kliknięciu na pobierz - pojawia sie tylko dymek rozpoczęto pobieranie i cisza... nic wiececj sie nie dzieje.

Firefox 68.0b10 (64 bity)
Tampermonkey 4.9.5941

**Comment by zacny** [comment]
Ja nie mogę odtworzyć takiej sytuacji, mam ff 67.0.2. Spróbuj na wersji 67 jak możesz. Możliwe, że w 68 weszło coś nowego co komplikuje sytuację.
upewnij się, że dobrze skonfigurowałeś plugin, możesz to sprawdzić dodając do skryptu:
```javascript
console.log(GM_info.downloadMode)
```
Powyższe powinno wyświetlić: "browser"
Możesz też na stronie z linkami poekserymentować ręcznym ustawieniem tej opcji:
```javascript
localStorage.getItem('voddownloader.doNotwarnIfIncorrectPluginSettingsDetected');
localStorage.setItem('voddownloader.doNotwarnIfIncorrectPluginSettingsDetected', 'true')
localStorage.removeItem('voddownloader.doNotwarnIfIncorrectPluginSettingsDetected');
```
Próbowałeś przeinstalować plugin? Już klika razy w firefoxie miałeś dziwne akcje z tampermonkey. Raz nawet ignorował skrypt całkowicie, ale wyświetlał, że niby go odpala.

**Comment by DajMiliona** [comment]
A co zrobic aby dymek do pobierana byl lepiej widoczny?
chodzi o to, ze slabo widoczny jest w IPLA. Ledwo co widoczny...
![2019-06-18_12h51_53](https://user-images.githubusercontent.com/39501742/59676476-f2d3d880-91c7-11e9-896f-998a0050313e.png)

**Comment by zacny** [comment]
@DajMiliona która wersja skryptu? Jaka przeglądarka? Co tu się stało? Oglądasz na pełnym ekranie, co tam powinno niby być powiadomienie o zakończeniu pobierania? Nie umiem wróżyć...

**Comment by funplayertv** [comment]
> 
> 
> Ja nie mogę odtworzyć takiej sytuacji, mam ff 67.0.2. Spróbuj na wersji 67 jak możesz. Możliwe, że w 68 weszło coś nowego co komplikuje sytuację.
> upewnij się, że dobrze skonfigurowałeś plugin, możesz to sprawdzić dodając do skryptu:
> 
> ```js
> console.log(GM_info.downloadMode)
> ```
> 
> Powyższe powinno wyświetlić: "browser"
> Możesz też na stronie z linkami poekserymentować ręcznym ustawieniem tej opcji:
> 
> ```js
> localStorage.getItem('voddownloader.doNotwarnIfIncorrectPluginSettingsDetected');
> localStorage.setItem('voddownloader.doNotwarnIfIncorrectPluginSettingsDetected', 'true')
> localStorage.removeItem('voddownloader.doNotwarnIfIncorrectPluginSettingsDetected');
> ```
> 
> Próbowałeś przeinstalować plugin? Już klika razy w firefoxie miałeś dziwne akcje z tampermonkey. Raz nawet ignorował skrypt całkowicie, ale wyświetlał, że niby go odpala.

tak jak wspomniałem wczesniej, u mnie po zmianie ustawien zgodnie z zalecanymi, tak aby pokazał sie i uaktywnił guzik pobierania, jak rowniez po przeinstalowaniu wtyczki - wszystko działa ok. tj. pobiera sie bez problemu, przynajmniej na te chwilę :).

**Comment by zacny** [comment]
Dobra to zamykam.
