### ISSUE TITLE
vod / brak id

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#16]
pozwole sobie skopiowac treśc wątki:

@zacny pozwole sobie napisac tutaj topic, bo nie mam dostepu akruat do githuba, a poźniej zapomnne...

weźmy na obroty takie o to linki:

https://vod.pl/seriale/most-nad-sundem/tl7lyqm#0
albo
https://vod.pl/seriale/most-nad-sundem/bc3g159#0

(# - dodawany jest automatycznie po wejsciu na te www, wiec zakladam ze to bedzie problem głowny)

i teraz po wejsciu na te www, u mnie wysweitla się:

_Nie możemy wyświetlić filmu
Materiał nie jest dostępny w Twoim kraju
_

mvpId w obydu linkach istnieje w źrodłach tych stron
i teraz jak sobie podmienimy ID w tym linku niżej:

https://player-api.dreamlab.pl/?body[id]=1980088.1733158388&body[jsonrpc]=2.0&body[method]=get_asset_detail&body[params][ID_Publikacji]=1980088.1733158388&body[params][Service]=vod.onet.pl&content-type=application/jsonp&x-onet-app=player.front.onetapi.pl&callback=

to material sie odnajduje i json sie wyswielta, ale skrypt pokazuje:

Niestety natrafiono na problem, który uniemożliwił dalsze działanie

Nie udało się odnaleźć idetyfikatora.
Algorytm rozpoznawania identyfikatora wideo na stronie: "https://vod.pl/seriale/most-nad-sundem/tl7lyqm#0" zakończył się niepowodzeniem. Może to oznaczać błąd skryptu.

Informacje o systemie: Firefox 60.0 32-bit on Windows 10 64-bit
Wersja pluginu: 4.9.5921

a teraz odpowiadajac na dalsze Twoje pytanie, tutaj zamieszczam source ze strony:

`https://pastebin.com/raw/43UGc0eq`

sprawdzilem na wszelki wypadek raz jescze co sie stanie po wpisaniu do konsoli:

 $(".mvp").attr('id')

i dostaje zwrotkę

undefined

**Comment by funplayertv** [comment]
jescze skopiowalem źrodło storny przez F12 i inspektora, zamiast klikac pokaz źródlo storny.... 

https://pastebin.com/raw/CyLxppfM

**Comment by zacny** [comment]
O tak lepiej, bo zawiera wszystko to co się dociągnęło.

**Comment by funplayertv** [comment]
prawda i widac, ze brakuje '        <div class="mvp" id="mvp:1980088.1733158388"> '

**Comment by zacny** [comment]
tak nie ma tego, dlatego aktualna metoda nie działa

**Comment by zacny** [comment]
powinno być ok
