### ISSUE TITLE
nowy serwis arte.tv

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#18]
nawiązując do tematu:
https://greasyfork.org/pl/forum/discussion/59205/x

ja ze swojej strony proponuje Arte.tv... wydaje sie do zrobienia, tym bardziej ze pozwoliłem sobie zrobić dla Ciebie @zacny szybki research i znalzałem: https://gorilla.moe/arte.tv-video-downloader-tampermonkey-greasemonkey-script 

i to działa... 

dodatkowo jescze znalazłem: 
https://gist.github.com/mledoze/7119779

wiec mozna uzyskac bez problemu rozwne wersje mp4 i polskie i inne jezyki itd.

przykładowy link:
https://www.arte.tv/pl/videos/079474-057-A/re-zestarzec-sie-w-domu/

**edit**

dla powyższego adresu... json wyglada tak:
https://api.arte.tv/api/player/v1/config/pl/079474-057-A

dla np. takiego:
https://www.arte.tv/pl/videos/049509-000-A/jharia-kraina-ognia/
json:
https://api.arte.tv/api/player/v1/config/pl/049509-000-A

**edit 2**

kolejny przykład 
https://api.arte.tv/api/player/v1/config/pl/087493-001-A
dla https://www.arte.tv/pl/videos/087493-001-A/pajace-ruggera-leoncavalla/

**Comment by zacny** [comment]
@funplayertv spokojnie do ogarnięcia to jest

**Comment by xxcriticxx** [comment]
https://github.com/JannikArndt/arte-downloader

**Comment by funplayertv** [comment]
tak sobie jescze pozwole napisac, bo byc moze @zacny sie nad tym zastanawia... oczywsice nie filtrowałbym tylko jezyka polskiego... bo w materiałach art. czesto jest tak ze czesc jste tylko po niemiecku albo ang np. opery i inne koncerty z festiwali... wteyd bysmy trafili linki, po prostu wyswietlałbym wszystko co dostepne ale posrtowne: jezykowo i jakościowo, fajnie jakby polska (o ile jest) była na górze...

**Comment by zacny** [comment]
Done
