### ISSUE TITLE
playpuls.pl

### ISSUE THREAD

**Issue by xxcriticxx** [zacny/voddownloader#19]
to ja zrobie request na play+

**Comment by funplayertv** [comment]
z tego co pamietam  (chyba ze cos sie zmieinło...) to nie da rady tam wyciagac mp4, chyba ze znasz metode? dostep do api etc ?

**Comment by zacny** [comment]
tutaj jest hls, można użyć np: hls downloadera - rozszerzenie w chrome.

**Comment by xxcriticxx** [comment]
Nie marnujmy czasu jak to coś ciężkiego
