### ISSUE TITLE
bład player.pl

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#2]
w skrypcie jest jeszcze jeden bład, który uniemożliwia pobranie np. takiego materiału:

https://player.pl/filmy-online/czlowiek-na-krawedzi,141868 gdzie bezproblemowo jest on pobierany przez stara wersje zakładki:
https://player.pl/api/?platform=ConnectedTV&terminal=Panasonic&format=json&authKey=064fda5ab26dc1dd936f5c6e84b7d3c2&v=3.1&m=getItem&id=141868

to samo dla adresu np.: https://player.pl/filmy-online/street-dance-2,106166

**Comment by zacny** [comment]
Wersja 5.2.8 powinna to naprawić.
