### ISSUE TITLE
arte.tv / versionLibelle

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#21]
proponuje zmienic "versionShortLibelle" na "versionLibelle" lepiej wygląda i daje wiececj do zrozumienia sformułowanie:

>         "versionLibelle": "Polski  (napisy) ", 

niż

>         "versionShortLibelle": "POL"

albo nawet:

>         "versionLibelle": "Musical (oryginał)",

zamiast

>         "versionShortLibelle": "MUS"

**Comment by HerMajestyDrMona** [comment]
versionShortLibelle może być przydatne do identyfikacji wersji językowej dla użytkowników nieznających polskiego.
https://github.com/zacny/voddownloader/commit/9b81dc34b353f0a330e082c1ee9ae114f2b1964a
Na razie będzie w stylu: versionLibelle + [versionShortLibelle]. Zobaczymy co zacny powie.

**Comment by funplayertv** [comment]
> 
> 
> versionShortLibelle może być przydatne do identyfikacji wersji językowej dla użytkowników nieznających polskiego.
> [9b81dc3](https://github.com/zacny/voddownloader/commit/9b81dc34b353f0a330e082c1ee9ae114f2b1964a)
> Na razie będzie w stylu: versionLibelle + [versionShortLibelle]. Zobaczymy co zacny powie.

wydaje mi się ze lepiej pod wzgledem czytelnosci zachowac taki format:

> [POL] Bitrate: 1500, Polski (napisy)

jak dla mnie czytelniej to wygląda niż

> Bitrate: 1500, Polski (napisy)[POL] 

no ale to kwestia do dyskusji itd.

**Comment by HerMajestyDrMona** [comment]
Przeniesienie krótkiej nazwy przed bitrate byłoby niespójne z wszystkimi innymi VOD. Z zasady mamy info po bitrate i myślę że tego się lepiej trzymać. Krótka nazwa przed pełną też nie prezentowała się za dobrze:
Bitrate: 2200, [PL] Polski (napisy)
ze względu na numer, przecinek, kwadratowy nawias jakoś mi się nie podobało w tej kolejności.
No ale kwestia dyskusyjna, zmiany nie poszły jeszcze do głównego skryptu, dopóki zacny nie sprawdzi.

**Comment by funplayertv** [comment]
racja, po prostu jakos razi mnie taka zbitka nawiasów )[, moze nawet juz lepiej byloby:

**Comment by funplayertv** [comment]
a gdyby cały string wyglądał tak i zmienial sie w zależnosci od serwisu....

`rozdzielczość: 1280x720, bitrate: 1500, jakość: HD, język: [POL] (Polski napisy PL);`

?

**Comment by zacny** [comment]
można tak zrobić ale kolejność będzie nieco inna

**Comment by funplayertv** [comment]
> 
> 
> a gdyby cały string wyglądał tak i zmienial sie w zależnosci od serwisu....
> 
> `rozdzielczość: 1280x720, bitrate: 1500, jakość: HD, język: [POL] (Polski napisy PL);`
> 
> ?

ewentualnie, jezeli miałoby to zmienic estetykę to tak:

`

> **rozdzielczość**: 1280x720, **bitrate**: 1500, **jakość**: HD, **język**: [POL] (Polski napisy PL);

`

**Comment by zacny** [comment]
Nie widzę tam informacji o jakości. Nie chce mi się przekształcać jednych oznaczeń na inne, bo to bez sensu, więc rozdzielczość musi wystarczyć:
https://www.youtube.com/watch?v=ytSsGn3E-ic
Co do języka zostawiłem długie oznaczenie w opisie, ale po krótkim sortujemy, co będzie dawało POL na szczycie wyników dopóki nie wprowadzą dodatkowych kodów językowych dalej w alfabecie niż powyższy. Dodałem też detekcję języka preferowanego przez użytkownika (api zwraca dane w różnych językach).

**Comment by funplayertv** [comment]
pięknie to Terra wygląda! 

> Nie widzę tam informacji o jakości. 
w przytaczanym stringu chodizło mi bardziej o reszte vod'ów niz ten konkretny i bardizej o schemat niz o to aby szukac/dodawac 'jakość' do materialow z arte ;)

**Comment by funplayertv** [comment]
> 
> 
> dopóki nie wprowadzą dodatkowych kodów językowych dalej w alfabecie niż powyższy. Dodałem też detekcję języka preferowanego przez użytkownika (api zwraca dane w różnych językach).

https://www.arte.tv/pl/videos/090168-000-A/nabucco-giuseppe-verdiego/ tutja mamy chyba taki przykład? włoski jest wyzzej niz polski ?

**Comment by zacny** [comment]
versionShortLibelle: "subDE"

**Comment by HerMajestyDrMona** [comment]
Chyba że duplikować versionShortLibelle i przed sortowaniem str.replace("sub", "");
Ale to bez sensu tak komplikować.

**Comment by funplayertv** [comment]
> 
> 
> Chyba że duplikować versionShortLibelle i przed sortowaniem str.replace("sub", "");
> Ale to bez sensu tak komplikować.



> 
> 
> versionShortLibelle: "subDE"
> Czyli nie chyba po czym posortować, skoro takie kwiatki.

albo moze w takich sytuacjach po prostu wyrożniac jakims innym odcieniem text dla POL ? normlanie bedzie zawsze na gorze, jak pojawi sie wyjatek to ustawic inny kolor? ciemniejszy or sth ?

**Comment by HerMajestyDrMona** [comment]
Ewentualnie kopiować wszystko do nowego "virtualnego" jsona, najpierw sprawdzając czy versionShortLibelle == "POL" (i inne), a potem w drugim loopie, już w kolejności alfabetycznej w dół wszystko co zostało.

**Comment by zacny** [comment]
Głupio zrobiłem to sortowanie ale działa.

**Comment by funplayertv** [comment]
potwierdzam, działa jak na szybkie kilka testów :)
