### ISSUE TITLE
.actions-row dla stylu

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#23]
o ile mozna dostosowywac wyglad pod siebie jescze to dokonalbym takiej zmiany:

ustawilbym:

```
.actions-row {
    width: 20em;
}
```

co da efekt:
![obraz](https://user-images.githubusercontent.com/50556762/60244051-e6333c80-98b9-11e9-84cc-49fcdd887f95.png)

zamiast:
![obraz](https://user-images.githubusercontent.com/50556762/60244089-f814df80-98b9-11e9-9dcd-6a95748b4b81.png)

wg mnie wyglada to lepiej... estetyczniej

**Comment by zacny** [comment]
Gorzej jak będzie inna czcionka, lub nie dociągnie styli. Zapas zostawiłem celowo, ale może niepotrzebnie.

**Comment by funplayertv** [comment]
> 
> 
> Gorzej jak będzie inna czcionka, lub nie dociągnie styli. Zapas zostawiłem celowo, ale może niepotrzebnie.

to wtedy się zmieni, jescze mi osobiscie nie zdazyło sie w trakcie uzywania ze style sie nie zaciagnely czy cos...

**Comment by HerMajestyDrMona** [comment]
U mnie w rozdzielczości 4k, przy 20em wygląda następująco: https://i.imgur.com/EVxfJd8.png

**Comment by funplayertv** [comment]
a przy 21 ?

**Comment by HerMajestyDrMona** [comment]
21em normalnie, ale ktoś może używać większych czcionek/skalowania.
Nie da się tego jakoś zautomatyzować? Żeby przyciski były tylko wyświetlane w jednej linii, a rozmiar wiersza zawsze 100% ich sumy?

**Comment by zacny** [comment]
pomyślę czy można coś z tym zrobić

**Comment by funplayertv** [comment]
@zacny  widze ze pozmieniałes CSS'a

teraz jest 

```
.actions-row {
    width: 19rem;
```

moje pytanie....

czy jakbys dał 18, byłoby dalej spoko dla Ciebie?
wizualnie wyglada to bardizej symetrycznie...

fajnie jakby @HerMajestyDrMona potwierdizł czy i jak to teraz u niego wyglada i czy jak by ustawił jednak 18. to czy dalej byłoby ok?

**Comment by zacny** [comment]
Nie nie jest. Zostawiłem marginesy i wyśrodkowałem tekst.
