### ISSUE TITLE
propozycja / adres wyniku skryptu

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#24]
nie wiem czy to jest możliwe do rozwiązania od strony technicznej, dlatego jezeli nie to od razu temat do zamkniecia, ale pomyslalem, ze ciekawym rozwiązaniem było by cos takiego... i tutaj pozwole sobie opisac bo własciwie nie wiem jak to nazwac w kilku slowach.

powiedzmy wchodze sobie na dany materiał, dajmy na to: https://www.arte.tv/pl/videos/090168-000-A/nabucco-giuseppe-verdiego/, klikam w 'pobierz wideo'

otwiera sie nowa zakładka, z wynikiem działania skryptu, linkami itd.

i teraz.... 

w pasku adresu oczywiscie jest pustka.... po porstu otwiera sie nowa zakładka

ale... czy jest techniczna możliwosci, aby jednak w pasku adresu pojawiał sie jakis string specialny, zawierajacy zakodowany adres materialu dla ktorego został wykonany wynik z jakims specialnym prefixem... 

zeby np. osoby, ktore MAJA aktywny skrypt po wpisaniu tego własnie ciagu znaków, od razu uzyskały wynik skryptu ?

nie wiem za bardzo czy @zacny  rozumiesz o co mi chodiz, chetnie opisze inaczej, ale daj cyne...

moznaby np. dzieki temu podsyłac znajomym taki ciag, oni klikaja i od razu maja wynik skryptu... dla danego materialu...

**Comment by HerMajestyDrMona** [comment]
Nie wiem czy można zmieniać adres, ale jak już to trzeba byłoby dodać pełen link do materiału VOD z poprzedniej strony i coś po #hashu typu #VODDOWNLOADERLINK, aby uniknąć ?get i tym samym uniemożliwić śledzenie lub blokowanie takich zapytań. Materiał otwierałoby się normalnie, ale przycisk "pobierz" symulowały się sam. Jest to wymagane do wyciągnięcia.

**Comment by zacny** [comment]
Chciałbyś mieć możliwość przesłania komuś rezultatów skryptu? Przecież ten skrypt wykonuje się u Ciebie lokalnie. Nie ma po tym śladu nigdzie. Nawet gdyby zrobić jakiś rozwiązanie, które uruchomiłoby skrypt z automatu to:
1. Przeglądarka zablokuje wystakujące okno
2. Serwer voda może wycinać parametry, których nie zna (nawet powinien)
3. Linki są generowane dla danego IP (przynajmniej w niektórych przypadkach tak jest), co może uniemożliwiać ich działanie u innych osób.
4. Jest funkcjonalność kopiowania adresu materiału, który można przesłać do kogoś

**Comment by funplayertv** [comment]
> 
> 
> Chciałbyś mieć możliwość przesłania komuś rezultatów skryptu? Przecież ten skrypt wykonuje się u Ciebie lokalnie. Nie ma po tym śladu nigdzie. Nawet gdyby zrobić jakiś rozwiązanie, które uruchomiłoby skrypt z automatu to:
> 
>     1. Przeglądarka zablokuje wystakujące okno
> 
>     2. Serwer voda może wycinać parametry, których nie zna (nawet powinien)
> 
>     3. Linki są generowane dla danego IP (przynajmniej w niektórych przypadkach tak jest), co może uniemożliwiać ich działanie u innych osób.
> 
>     4. Jest funkcjonalność kopiowania adresu materiału, który można przesłać do kogoś

no i juz do mnie dotarło, ze to bezsensowne by było, do zamknięcia w takim razie :).

**Comment by HerMajestyDrMona** [comment]
>3. Linki są generowane dla danego IP (przynajmniej w niektórych przypadkach tak jest), co może uniemożliwiać ich działanie u innych osób.

Masz rację, dyskwalifikuje to przede wszystkim kwestia wyskakujących okienek, ale:
- #Hash po linku mógłby być sprawdzany jak tylko strona zaczyna się ładować i stąd skrypt wiedziałby że ma "kliknąć" pobierz.
- Oryginalna strona VOD by się załadowała, stąd wszystko dałoby się wyciągnąć z kodu strony, zarazem tworząc nowe linki dla nowego IP.

Mimo wszystko bezsensowne kombinowanie, bo skoro użytkownik końcowy musi mieć zainstalowany skrypt to równie dobrze kliknie sobie "Pobierz".

**Comment by zacny** [comment]
W zasadzie tak, tylko skrypt czeka na załadowanie się elementów strony więc nie może od razu się uruchomić, bo parsowanie identyfikatora nie zadziała. Hash z kolei, jeżeli coś go nie usunie to przynajmniej powoduje przerobienie większości algorytmów parsowania id. 
@HerMajestyDrMona W zasadzie to jak by nie było przeszkód to może to jest do zrobienia, choć ja nie widzę w tym większego sensu. Możesz spróbować dodać.

**Comment by HerMajestyDrMona** [comment]
> czeka na załadowanie się elementów strony więc nie może od razu się uruchomić, bo parsowanie identyfikatora nie zadziała
Chyba że osobna funkcja sprawdza i zmienia "false" na "true" w window.variableName. Potem po załadowaniu skrypt może sprawdzać po "window.variableName" i na podstawie tego symulować kliknięcie.

Natomiast to i tak nie ma sensu, wyskakujące okienko i tak byłoby zablokowane. Po prostu na przyszłość jakbyśmy potrzebowali hasha wykorzystać do czegokolwiek innego (co jest mało prawdopodobne) to mamy "wymyślony" sposób.
