### ISSUE TITLE
Warsaw shore na player.pl

### ISSUE THREAD

**Issue by Berbeloch** [zacny/voddownloader#27]
Jest jakieś rozwiązanie na brak możliwości ściągania tego reality show z playera.

Wiekszosc rzeczy ściągam bez problemu, a tu nawet poł odcinka nie idzie zagrabić. 

Chodzi dokładnie o Warsaw Shore - ekipa z Warszawy ktore jest dostepne na player.pl

**Comment by funplayertv** [comment]
link, link, link jescze raz link... nikt tu nie jest wrozką, nie mamy tez ządnego Mocarnego drzewa pytań i odpowiedzi, wiec ułatwisz, jak bediz elink :)

**Comment by Berbeloch** [comment]
https://player.pl/programy-online/warsaw-shore-ekipa-z-warszawy-odcinki,4365/odcinek-4,S07E04,70992

**Comment by funplayertv** [comment]
U mnie działa ten link bez problemu.

**Comment by Berbeloch** [comment]
W sensie ściąga normalnie na dysk?

**Comment by HerMajestyDrMona** [comment]
Tak, u mnie też. Chociaż po 3 pierwszych minutach prawie mi oczy wypaliło.

**Comment by Berbeloch** [comment]
To nie jest kwestia treści, bo to nie dla mnie to gówno tylko dla klientów.

U mnie wczoraj pokazywało okienko z jakościami, odtwarzało odcinki, ale po kliknięciu w ZAPISZ wyskakiwało niby okienko że zacznie pobierać ale juz nie pobierało. Nadmienie że ściągnąłem wczoraj kilka sezonów innego badziewia, ale to nie chciało sie pobierac za nic

**Comment by HerMajestyDrMona** [comment]
Możesz klikać "Odtwórz" i kiedy pojawi się okienko z materiałem: CTRL+S aby zapisać. Mniej wygodne, bo trzeba też ręcznie nazwę pliku zmienić, ale w takich wypadkach to chyba jedyne wyjście.

**Comment by Berbeloch** [comment]
Ok. Super. Czyli jednak mogło być coś na rzeczy.

Po pracy od razu spróbuję. Dziękuję.
