### ISSUE TITLE
rezultat skryptu otwiera się w ramce danego materiału zamiast w nowej karcie

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#28]
kolega @HerMajestyDrMona  wpsomniał o tym we wcześniejszym temacie, ja natomiast potwierdzam ze tak sie dzieje... jezeli wejdziemy np. na: https://vod.pl/seriale/przygody-tarzana/fs6qczh#0 klikamy na pobierz video i pojawi si enowa karta z rezultatem... i teraz na tej nowej karcie z rezultatem wpiszemy adres innego materiąlu z vod.pl (chociaz pewnie zadziała to tak samo jakbysmy wpisali player.pl itd. ) to po kliknieciu na pobierz video wyswietli sie rezultata na tej własnie stronie z materialem w ramce u gory storny...

firefox.

**Comment by zacny** [comment]
powinno być ok

**Comment by funplayertv** [comment]
wygląda ok... na szybko nie moge zreplikowac juz tego błędu :(

**Comment by zacny** [comment]
Bo to było pokłosie ostatnich zmian.
