### ISSUE TITLE
nowa funkcja / autoclose

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#29]
a co jakby była mozliwośc.... do wyboru, na zasadzie zaznaczenia tak/nie aby mozna było zaznaczyć... 

'Automatycznie zamknij karte z materialami po wykonaniu akcji:
- otwórz
- kopiuj
- zapisz
"

no bo własciwie po co mi karta z materialami kiedy klkine otwórz a i tak otwiera si enowa zakładka i tam juz sobie ogladam....

**Comment by HerMajestyDrMona** [comment]
Gorzej jak jeden z materiałów ma problemy (np. 404). Takie zamykanie karty ze skryptem wywoływało by nowy komunikat błędu i nie dałoby rady zrobić żadnej innej akcji oprócz pierwszej wybranej. Lepiej jak użytkownik ma nad tym kontrolę, zwłaszcza jeśli jest to kwestia przesunięcia myszy i jednego kliknięcia.

**Comment by zacny** [comment]
Nie. To jest niepotrzebna komplikacja. W skrypcie nie ma też jakiegoś okna z opcjami, na którym dałoby się to wygodnie przestawiać. Potencjalnie stworzyłoby to raczej więcej problemów i pytań.
