### ISSUE TITLE
brak vodapitvp

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#3]
zostawie tutaj, bo bedzie czytelniej, a więc...

dobrze bybyło dodać/naprawić obsługę materiałow, które sa dostepne przez API, dla przykładu:
https://vod.tvp.pl/video/wiadomosci,17052019-1200,42549669 tutaj json sie nie pobierze standardową metodą czyli https://www.tvp.pl/shared/cdn/tokenizer_v2.php?object_id= otrzymamy 

```
url
status NOT_FOUND
videoId 42549669
platform sdt-v2
userIp
adaptive false
live false
title
duration 900
countryIsDefault false
mimeType unknown
ads_enabled true
payment_type 0
distribution_model
```

zeby to naprawić i zeby mozna było pobrac odpowiedni plik json trzeba skorzystac z linku (dokładnie wczesniejszy skrypt z miniskrypt tak działał/działa)
https://apivod.tvp.pl/tv/video/42549669/ tutaj po podaniu autoryzacji  api/vod otrzymamy odpowiedni plik json.

tak jak zauwayzłem i napisałem na forum, wyglad ana to ze inne materiąły sa tez dostepne przez te metode, natomiast niekotre zdaja się byc dostepne tlyko przez te metode API.

tzreba by sprawdzać najpierw czy działa przez tokenizer a jak nie sprawdzać przez apivod dopiero w zaleznosci od tego co sie wydarzy wysweitlac link :)

źródło na forum:
https://greasyfork.org/pl/forum/discussion/57515/x

edit.
dodam jescze na przykłądu pewną rzecz....

mamy sobie materiały:
1. https://teleexpress.tvp.pl/42405307/19052019-1700
2. https://vod.tvp.pl/video/teleexpress,19052019-1700,42549812

i teraz, dla numerka 2... skrypt reaguje i wyświetla guzik umozliwiajacy pobranie, ale niestety nie bedzie działać przez sytuacje opsiana powyzej.

dla numerka 1, skrypt nie wyswietla zadnego guzika, ale jak ręcznie wpiszemy: https://www.tvp.pl/shared/cdn/tokenizer_v2.php?object_id=42405307 to otrzymujemy poprawny json

**Comment by zacny** [comment]
@funplayertv dzięki zajmę się tym niebawem

**Comment by zacny** [comment]
Próbowałem poniższych zapytań. Wszystko się rozbija o CORS „Access-Control-Allow-Origin”
`
$.ajax({
    dataType: "json", 
    method: "GET", 
    url: "https://apivod.tvp.pl/tv/video/42549669/", 
    password: "vod", 
    username: "api", 
    success: function(){
        console.log('JUPI')
    }
});

$.ajax({
    dataType: "json", 
    method: "GET", 
    url: "https://apivod.tvp.pl/tv/video/42549669/", 
    beforeSend: function (xhr) {
        xhr.setRequestHeader ("Authorization", "Basic " + btoa("api:vod"));
    },
    success: function(){
        console.log('JUPI')
    }
});

$.ajax({
    dataType: "json",
    method: "GET", 
    url: "https://apivod.tvp.pl/tv/video/42549812/", 
    headers: {
        "Authorization": "Basic " + btoa("api:vod")
    },
    success: function(){
        console.log('JUPI')
    }
})

$.ajax({
    dataType: "jsonp",
    url: "https://apivod.tvp.pl/tv/video/42549669/",
    jsonpCallback: function(json){
        console.log(json)
    }
})
`

**Comment by funplayertv** [comment]
tutaj patrzyłes ?

https://stackoverflow.com/questions/1652178/basic-authentication-with-xmlhttprequest 
i 
https://stackoverflow.com/questions/45533002/basic-authentication-with-header-javascript-xmlhttprequest

**Comment by zacny** [comment]
To nie kwestia tego, że nie mogę się zautoryzować. To się udaje. 
Nie można pociągnąć jsona z innej domeny, chyba że konfiguracja serwera to umożliwia, a przynajmniej jeszcze nie znalazłem na to sposobu.

**Comment by funplayertv** [comment]
a jakas manipulacja nagłowkami? bez tworzenia proxy itd. ?

**Comment by HerMajestyDrMona** [comment]
Jakimś cudem w naszym skrypcie, w wersji 4.9 to działa.

**Comment by zacny** [comment]
Znalazłem coś takiego:
http://www.ajax-cross-origin.com/
Wygląda, że to działa.

**Comment by zacny** [comment]
Domena apivod.tvp.pl nie pozwala na zaciągnięcie tego jsona z innych domen. Szczegóły tutaj:
https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy. 
Nie widzę ładnego sposobu by to zrobić.

**Comment by aleks365** [comment]
Musiałbyś postawić serwer, który by wysyłał request do "apivod.tvp.pl" i odbierał te dane twoim skryptem ;)
Daje 100% gwarancji, że to zadziała. Problemem jest to, że musiałbyś utrzymywać serwer

**Comment by aleks365** [comment]
Spójrz:
![image](https://user-images.githubusercontent.com/42388710/58282761-f5006e00-7da6-11e9-893b-4b3289aa7d15.png)
Serwer lokalnie uruchomiłem ale na vps i tym podobnych też działa

**Comment by funplayertv** [comment]
alternatywnie, o ile jest taka możliwość, autoryzować, i wyswietlić nowa zakłądkę z jsonem ale bezpośrednio pod adresem danej lokalizacji, czyli tak jakby po porstu wyswietlic nowa zakłądkę i/albo juz z autoryzacja zeby nie trzeba było wpisywac, albo po porstu wymagac autoryzacji

**Comment by aleks365** [comment]
Z poziomu przeglądarki tego się raczej nie zrobi, bo z tego co wiem, to przeglądarka nie pozwala wysłać requesta i wywala komunikat CORS

**Comment by funplayertv** [comment]
https://stackoverflow.com/questions/49158/greasemonkey-script-to-auto-login-using-http-authentication

**Comment by HerMajestyDrMona** [comment]
Stara wersja (4.9) wyciąga ID materiału jako: 42383664
Nowa jako: 42549669

I dzięki temu działa.

**Comment by funplayertv** [comment]
skąd ta różnica? przecież materiał: https://vod.tvp.pl/video/wiadomosci,17052019-1200,42549669 ma ID
42549669;

nie widze nigdzie id 42383664

**Comment by HerMajestyDrMona** [comment]
Ramka jest z numerkiem 42383664:

<iframe id="tvplayer" src="/sess/tvplayer.php?object_id=42383664&amp;autoplay=true&amp;nextprev=1&amp;vastTransformer=1.13.1" name="tvplayer" class="tvplayer tvpstatepaused fit-height" width="100%" height="100%" frameborder="0" scrolling="no" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>

I z tej ramki spróbuję wyciągnąć object_id. Może zacny poprawi/ulepszy żeby nie sypało błędami w razie problemów.

**Comment by funplayertv** [comment]
ale to nic nie da, zauważ, ze nawet jak pobierzez ID 42383664 za pomoca https://www.tvp.pl/shared/cdn/tokenizer_v2.php?object_id=42383664 otrzymasz jsona, ALEEEEE do plikow video max "totalBitrate":820000, a z apomoca api - juz normalna jakosc :)

**Comment by HerMajestyDrMona** [comment]
Nie rozumiem? Wersja 4.9 wyciąga te wiadomości w 9100000, takiej samej jak jakiś pseudo-serial.

**Comment by funplayertv** [comment]
zgadza się, juz miałem edytowac, moj bład, faktycznie, gdy sie pobierze ten ID z iframe o ktorym mowisz, nawet za pomoca https://www.tvp.pl/shared/cdn/tokenizer_v2.php?object_id=42383664 to działa, poprawnie

**Comment by HerMajestyDrMona** [comment]
Heh, tylko oni blokują tą ramkę jak adblock jest włączony, więc ciężko jest wyciągnąć ten numerek od razu.

**Comment by HerMajestyDrMona** [comment]
Mam taki pomysł:
- Sprawdzanie czy JSON jest poprawny wg. nowej metody. Jeśli nie to szukanie czy ramka z tekstem object_id istnieje.
- Jeśli nie istnieje, to na tej nowej karcie (co wyświetla linki) można dodać informację czerwoną czcionką aby wyłączyć Adblocka i spróbować ponownie.

Mogę się tym zająć, tylko że ja piszę tym brzydkim, niespójnym Javascriptem więc będzie do poprawy. @zacny napisz proszę czy sam chcesz to zrobić, żeby nie powtarzać tego samego.

**Comment by zacny** [comment]
Obczaję to co mówicie. @aleks365. Czy to co zrobiłeś da się jakimś prostym skryptem php zrobić? Jeżeli tak to można coś nawet darmowego skonfigurować (najwyżej będzie się zamulać). Obczaję też czemu jest różnica w ID. Ja na wersji 4,9 w ogóle nie miałem przycisków, nawet jak się adbloki wyłączyło.
Ostatecznie jak nic nie wymyślę, to zrobię rozwiązanie takie, że dam linka do tego api o tak:
https://api:vod@apivod.tvp.pl/tv/video/42549669
To działa przecież :)

**Comment by zacny** [comment]
@HerMajestyDrMona widzę tylko jedną ramkę. Brak podanego przez Ciebie ID.

**Comment by HerMajestyDrMona** [comment]
@zacny, a materiał się odtwarza w ogóle? Jakieś reklamy lecą itd.?

**Comment by aleks365** [comment]
@zacny 
Pewnie, że się da ;)
Łap:
```php
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://apivod.tvp.pl/tv/video/42549669/",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "Authorization: Basic YXBpOnZvZA==",
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

**Comment by zacny** [comment]
U mnie to wygląda tak. Co bym nie zrobił to mam wyłączyć blokadę. 
- Wyłączenie adbloka i ctrl+f5
- wyłącznie i restart
- odlistalowanie i restart przeglądarki
Oni mnie mają chyba na jakieś czarnej liście :) albo konkretnie ktoś ... tę funkcjonalność

**Comment by zacny** [comment]
@aleks365 Dziękuję

**Comment by HerMajestyDrMona** [comment]
@zacny, nie używasz przypadkiem PiHole, albo jakiegoś innego filtrującego DNSa? W moim przypadku właśnie trzeba było PiHole pauzować.

**Comment by zacny** [comment]
@HerMajestyDrMona no mam PiHole... eh zawsze o tym zapominam.

**Comment by zacny** [comment]
@HerMajestyDrMona Faktycznie jest ramka, ale nie działa na firefoxie u mnie, na chromu już mu lepiej. Dobra zrobię taką zmianę, że będzie wykrywało tę ramkę jeżeli jest. Choć używanie tego serwisu bez blokowania reklam to jest jakiś masochizm.

**Comment by aleks365** [comment]
> @aleks365 Dziękuję i proszę jeszcze o słowo wyjaśnienia jak mam tego skryptu użyć. Mam go po prostu odpalić? Odpaliłem sobie tutaj:
> https://voddownloader.000webhostapp.com/apitvp.php
> i mam taką odpowiedź od serwera:
> `{"success":0,"error":500,"message":"Undefined class constant 'ERROR_CODE_GEO_BLOCK_MSG'","version":"v2","data":[]}`
> Jakaś inna wersja php? Z PHP to prawie wcale nie miałem do czynienia więc nie znam nawet podstaw podstaw.

Ja mam wersje php 7.2.9 do tego musisz mieć zainstalowany moduł php-curl... Zobacz czy serwer na których masz skrypt obsługuję curl, ale obawiam się, że mają to wyłączone bo to darmowy hosting

**Comment by funplayertv** [comment]
@zacny @HerMajestyDrMona  no własnie, wyjasniło sie dlaczego na firefoxie u mnie tej ramki tez nie ma, ale ten sam problem mam, mimo ze mam wyłączonego ublocka to i tak jest dupa, a nie uzywam PiHole ani nic z tych rzeczy... mysle ze wiecej bedzie takich ludzi, wiec fajnie bybyło wymyslic jakas taka metode ktora byłaby odporna na te sytuacje....

**Comment by HerMajestyDrMona** [comment]
A co z tym [apivod](https://apivod.tvp.pl/tv/video/42549669)? Różni się czymś? Nie działa przy jakichś materiałach?

Ewentualnie można zrobić 3 failbacki:
1. Obecna metoda
2. Szukanie ramki (i porównywanie czy nie jest to to samo ID co wcześniej)
3. apivod

Lub zamienić punkt 3 i 2 pozycjami.

**Comment by zacny** [comment]
@HerMajestyDrMona Obecna wersja zawiera obejście problemu. Wyświetlam linka do tego jsona i można sobie go kliknąć. Brzydkie wiem, ale na razie tylko tyle wymyśliłem.
Pomysł z:
> <iframe id="tvplayer" src="/sess/tvplayer.php?object_id=42383664&autoplay=true&nextprev=1&vastTransformer=1.13.1"

Nie bardzo można zrealizować. Nie można zjeść ciastka i mieć ciastka. Albo będzie dobrze dla przypadków gdzie ludzie mają poblokowane adbloki albo dla tych masochistów, który tego nie zrobili. Można to zaobserwować na obecnej wersji jeżeli zmienimy:
`'#tvplayer, div.playerContainer'`
na
`'#tvplayer'`
Jak są reklamy to tam jest wolna amerykanka i pełno ramek. Skrypt jest z uwagi na inne serwisy ustawiony tak, by uruchamiał się w każdej z ramek pasujących do dopuszczanych urli.
Więc w razie większej ilości przycisków jeden zakrywa drugi.
Jedyna nadzieja na normalne działanie jaką ja widzę to jest przygotowanie skryptu według pomysłu kolegi @aleks365 
Czyli js strzela do skryptu php albo innego na serwerze z id materiału, a on dla niego loguje się i ściąga jsona z api oraz przesyła dalej.

Jeżeli są inne racjonalne pomysły to chętnie przygarnę.

**Comment by HerMajestyDrMona** [comment]
> Nie bardzo można zrealizować. Nie można zjeść ciastka i mieć ciastka. Albo będzie dobrze dla przypadków gdzie ludzie mają poblokowane adbloki albo dla tych masochistów, który tego nie zrobili. 

Ale w czym dokładnie problem? Ten przycisk mógłby się wyświetlać w identyczny sposób jak teraz, tylko po kliknięciu, zmienić zachowanie funkcji po:
`if(data.status == 'OK' && data.formats !== undefined){`
dodać:
`else {
//Sprawdzenie czy Ramka istnieje
//Powtórzenie funkcji tym razem używając ID z ramki
}`
Być może gdzieś wcześniej da się sprawdzić czy Json jest OK i zmienić "url" jeszcze wcześniej? W najnowszej wersji pod:
`if(exception.name = 'API_ERROR'){`

A w przypadku braku ramki dopiero pokazać linka apivod? W ten sposób istnieje większa szansa że ktoś pobierze co potrzebuje, niżeli ręczne przeszukiwanie.

Dodatkowo, można też ustawić skrypt z Tampermonkeya żeby aktywował się na stronie "apivod.tvp.pl"
I wyświetlał potwierdzenie czy wyodrębnić linki w przyjaznej formie (albo w ogóle nie musiałby się pytać). Potem traktował innerHTML jako JSON i pokazywał wszystko w przyjaznej formie. Tak na Ipli stara wersja skryptu działała, Json w nowej karcie i pobieranie informacji o materiałach + sortowanie.

**Comment by aleks365** [comment]
@zacny 
Po przeanalizowaniu api tvp zauważyłem, że linki wideo są przypisane do IP itp dlatego jakby mój skrypt php wysyłał request do
https://apivod.tvp.pl/tv/video/
To linki przechwycone przez Twój skrypt by nie działały u użytkownika.

Napisałem prosty skrypt w nodejs do którego przekazujemy ID wideo i on sprawdza czy materiał kryje się pod innym ID czy pod takim samym

Przykład:
Tego wideo nie da się pobrać skryptem, ponieważ w api ma on inne ID
https://vod.tvp.pl/video/teleexpress,19052019-1700,42549812
Przesyłam ID tego wideo do mojego skryptu i w odpowiedzi dostaje poprawne ID
![image](https://user-images.githubusercontent.com/42388710/58342033-f639a580-7e4f-11e9-9099-b7617e6d78c6.png)

Otrzymane ID przesyłamy do:
https://www.tvp.pl/shared/cdn/tokenizer_v2.php?object_id=42405307
I otrzymujemy wszystko co niezbędne do dalszych akcji skryptu.

W sytuacji gdy wideo ma takie samo ID na stronie jak w api w odpowiedzi dostane to samo ID
![image](https://user-images.githubusercontent.com/42388710/58342461-b58e5c00-7e50-11e9-8b9e-c42c922f6fab.png)

Najlepszą wygodą dla użytkownika byłoby kliknąć i mieć wideo które go interesuje dlatego warto przyjrzeć się mojej propozycji

Skrypt można zrobić oczywiście również w php i rezultat otrzymamy taki sam

**Comment by HerMajestyDrMona** [comment]
Zewnętrzne VPSy mogą być banowane przez VODy, a w ekstremalnych warunkach zgłaszane za "ataki". Trzeba by wprowadzić limity na IP (np.
`if (!apcu_exists(){
apcu_store("Limit-".$_SERVER["REMOTE_ADDR"]),"blablabla", 5);//Dalszy kod
}`

Do tego kwestia telemetrii. Nie posądzając że ktoś zbierałby jakieś informacje o odwiedzinach, itd. to i tak połączenia do serwerów 3cich mogą być negatywnie odbierane przez użytkowników.

Dobrze byłoby pozostać przy wersji gdzie wszystko odbywa się lokalnie.

**Comment by aleks365** [comment]
Testowałem taki scenariusz i do żadnych blokach nie doszło
Przez 25 minut wysyłałem 100 zapytań do api w ciągu 2-3 sekund z jednego hosta i wszystko działa dalej także testy zaliczone.
Co do zbieraniu informacji to @zacny miałby dostęp przez ssh/sftp do skryptu ale jak tam uważasz w takim razie moja rola w tym momencie się kończy skoro skrypt ma lokalnie uzyskać poprawne id wideo.
Pozdrawiam i życzę rozwiązania problemu jak najszybciej

**Comment by HerMajestyDrMona** [comment]
Problem jest praktycznie rozwiązany w wersji 5.3.3. Pozostaje wyciągnąć linki z JSONa otworzonego w nowej karcie.

**Comment by funplayertv** [comment]
> 
> 
> @zacny
> Po przeanalizowaniu api tvp zauważyłem, że linki wideo są przypisane do IP itp dlatego jakby mój skrypt php wysyłał request do
> https://apivod.tvp.pl/tv/video/
> To linki przechwycone przez Twój skrypt by nie działały u użytkownika.
> 
> Napisałem prosty skrypt w nodejs do którego przekazujemy ID wideo i on sprawdza czy materiał kryje się pod innym ID czy pod takim samym
> 
> Przykład:
> Tego wideo nie da się pobrać skryptem, ponieważ w api ma on inne ID
> https://vod.tvp.pl/video/teleexpress,19052019-1700,42549812
> Przesyłam ID tego wideo do mojego skryptu i w odpowiedzi dostaje poprawne ID
> ![image](https://user-images.githubusercontent.com/42388710/58342033-f639a580-7e4f-11e9-9099-b7617e6d78c6.png)
> 
> Otrzymane ID przesyłamy do:
> https://www.tvp.pl/shared/cdn/tokenizer_v2.php?object_id=42405307
> I otrzymujemy wszystko co niezbędne do dalszych akcji skryptu.
> 
> W sytuacji gdy wideo ma takie samo ID na stronie jak w api w odpowiedzi dostane to samo ID
> ![image](https://user-images.githubusercontent.com/42388710/58342461-b58e5c00-7e50-11e9-8b9e-c42c922f6fab.png)
> 
> Najlepszą wygodą dla użytkownika byłoby kliknąć i mieć wideo które go interesuje dlatego warto przyjrzeć się mojej propozycji
> 
> Skrypt można zrobić oczywiście również w php i rezultat otrzymamy taki sam

bardzo ciekawa opcja i rozwiązanie wg mnie. chyba ze faktycznie da sie zrobić tak, jak pisał @HerMajestyDrMona  ze skoro juz skrypt wyświetli jsona, to tak jakby go ponownie przeszukac i wyciagnac linki z juz otworoznego jsona na karcie nowej... zamiast klikac recznie.

**Comment by zacny** [comment]
Zrobiłem nową gałąź: dev. Można sprawdzić czy nowe rozwiązanie działa. Za pierwszym razem api chce autoryzacji niestety.

**Comment by funplayertv** [comment]
Wygląda na to że działa tak testując na szybko, jedynie parę razy zdarzało się że pojawiał się błąd json error jakby pod video, ale nie mogę zte produkować tego jzeby powiedzieć co i jak... Ale fakt faktem rozumiem metoda z ramka udana?

PS api @ vod w linku nie uda? Coby nie wpisywać?

**Comment by aleks365** [comment]
Nie każdy zagląda na gita i skąd użytkownik skryptu ma znać login i hasło do api?
Skoro to już jest w taki dziwny sposób zrobione to lepiej zmienić
>urlTemplates: ['https://apivod.tvp.pl/tv/video/$idn'],

Na:
>urlTemplates: ['https://api:vod@apivod.tvp.pl/tv/video/$idn'],

I
> VideoGrabber.grabVideoDataFromJson = function(vod, templateIndex, w){
	        w = (w === undefined) ? window.open(): w;
	        var url = getUrl(vod, templateIndex);
	        return DomTamper.createIframe(url, w);
	    };

Zamienić na:

> VideoGrabber.grabVideoDataFromJson = function(vod, templateIndex, w){
            var url = getUrl(vod, templateIndex);
	        w = (w === undefined) ? window.open(url): w;
	        return DomTamper.createIframe(url, w);
	    };

Dzięki temu użytkownik nie musi autoryzować się do api.
Chociaż to i tak nie jest zadowalające rozwiązanie ale lepsze niż aktualne

**Comment by funplayertv** [comment]
@aleks365 - działa, ale u mnie np. standardowo lisek ostrzega o próbie zalogowania (mimo, ze samo zalogowanie juz nastapiło) to i tak wywala sie popup, co gorsza po kliknieciu ok, wyswietla się json czysty (a przed kliknieciem ok, wyswietlało sie formatowanie skryptu

**Comment by zacny** [comment]
Wiem dlatego takie rozwiązanie nie jest według mnie aceptowalne.

**Comment by funplayertv** [comment]
> 
> 
> Wiem dlatego takie rozwiązanie nie jest według mnie aceptowalne.

ok, a gdyby zrobić to tak jak Ty zrobiłes @zacny , ale wczesniej wyswietlić stronę z informacją na zasadzie:
"kliknij tutaj aby otrzymać linki (po pojawieniu sie okna z autoryzcjia wpisz: xxxx ", kliaksz, jestes poinformowany co wpisac, wyswietla Ci sie Json sformatownay i wsio hula. na około bo na około no ale coż...

**Comment by zacny** [comment]
Do iframe nie można wrzucać autoryzacji w url bo chrome blokuje i inni też mogą zacząć, poza tym dochodziłoby wykrywanie jeszcze kto ma jaką przeglądarkę.

**Comment by funplayertv** [comment]
dlatego mówie, poprzedzić Twoja implementację 'nową stroną' a na niej 'button' + komunikat na zasadzie:
"Materiał wymaga dodatkowej interakcji, kliknij tutaj i autoryzuj sie danymi: xxx xxx, aby uzsykac linki"

uzytkownik klika, pojawia sie okienko standardowe z autoryzacjia, autoryzuje, i pojawia sie nowa/albo odświeżona karta (jak sie da) ze sformatowanym jsonem przez skrypt.

**Comment by zacny** [comment]
Czy waszym zdaniem przed tym całym procesem powinna być też próba dostania się do plików przez tokenizer? Nie mam poności czy apivod posiada wszystko co tokenizer, więc moim zdaniem - tak.

**Comment by funplayertv** [comment]
zdrowy rozsądek podpowiada mi intuicyjnie, że tak - powinno być wszystko, ale biorąc pod uwagę, ze zazwyczaj nic nie jest zero jedynkowe to dla swietego spokoju ja osobiscie bym sprawdzał i tu i tu, bo moze byc tak ze czesc materiałow starszych np. (chociaz szukam i nie moge takiego znaleźć) przez api dostepna nie bedzie....

p.s. co do tego błedu o ktorym pisałem wczesniej:

![obraz](https://user-images.githubusercontent.com/50556762/58387038-e9ac7d00-8008-11e9-885f-a23478aa038f.png)

**Comment by zacny** [comment]
@aleks365 firefox za każdym razem przy url z autoryzacją, pokazuje komunikat typu prompt. W iframe już nie, ale za to chrome blokuje. Opery nie sprawdzałem. Firefox nie odpala skryptu tampermonkey na urlach z jsonem dopóki nie wyłączy się json viewera, a ten jest domyślnie włączony.

**Comment by aleks365** [comment]
@zacny Skoro chcesz wysyłać 2 zapytania do api to nie lepiej uderzyć najpierw do
`http://tvp.pl/pub/stat/videofileinfo?video_id=(ID)`
W odpowiedzi dostajesz "copy_of_object_id" jest to poprawne ID video które wysyłasz do tokenizera.
A w sytuacji gdy "copy_of_object_id" nie istnieje wtedy uderzasz do tokenizera z id pierwotnie pobranego ze strony.
Jedyny problem w tym to jakoś obejść trzeba cors.
Jeśli masz dobry pomysł na uderzanie do tokenzera i gdy nie istnieje video w tym api to uderzać do apivod to jak najbardziej też to według mnie jest w porządku

**Comment by zacny** [comment]
@funplayertv zapraszam na kanał slacka, bo robi nam się chat tutaj. Nie wiem czego tyczy się zrzut.

**Comment by zacny** [comment]
@aleks365 Nie rozważałem wcześniej takiej możliwości. Rozpoznam temat.

**Comment by zacny** [comment]
@aleks365 Obejście już mam działające, a to to api które podałeś nie wymaga autoryzacji. Według mnie w takim razie potrzebne są następujące kroki
- odnalezienie api na stronie
- weryfikacja z videofileinfo
- strzał do tokenizera
Czy sądzisz, że strzał do apivod jest jeszcze w tym potrzebny?

**Comment by aleks365** [comment]
Testowałem na kilkunastu materiałach videofileinfo i zawsze się sprawdzało, ale myślę że warto będzie jak również Ty przeprowadzisz kilka/kilkanaście prób.
Jak testy będą zaliczone to myślę, że apivod będzie zbędny

**Comment by funplayertv** [comment]
ja jescze chciałbym zwrocic uwage na jedną rzecz...
materiał: https://teleexpress.tvp.pl/42405307/19052019-1700 co prawda nie na vod.tvp, ale i tak skrypt tutaj nie reaguje, aleeee...

ID tego materiału to: 42405307;
jak strzelimy do videofileinfo uzyskamy:  https://www.tvp.pl/pub/stat/videofileinfo?video_id=42405307 - nie bedzie tutaj info o 'copy_of_object_id', wiec dane z videofileinfo  dla tego ID i tego materiału nic nam nie zorbią, ale jak stzrelimy do https://www.tvp.pl/shared/cdn/tokenizer_v2.php?object_id=42405307 to faktycznie uzyskamy json'a

gdy strzelimy tym smamym ID do apivod - rowniez json bedzie, po rpostu chciałem zwrocic uwage, ze moga sie zdarzyc materiąły gdzie nie bedzie 'copy_of_object_id';

**Comment by HerMajestyDrMona** [comment]
Ja mam taki pomysł, aby w nowej karcie otworzyć link do https://api:vod@apivod.tvp.pl/... (może w jakimś nowym, zminimalizowanym oknie, po kliknięciu na przycisk Pobierz)? A po sekundzie lub dwóch załadować to zwykłe apivod.tvp.pl do ramki. W ten sposób będziemy już autoryzowani przez normalne otwarcie karty w tle i ramka wyświetli się poprawnie. Przynajmniej tak mi się wydaje.

**Comment by aleks365** [comment]
> gdy strzelimy tym smamym ID do apivod - rowniez json bedzie, po rpostu chciałem zwrocic uwage, ze moga sie zdarzyc materiąły gdzie nie bedzie 'copy_of_object_id';

Właśnie oto chodzi bo zauważ, że niektóre materiały nie są dostępne przez tokenizer tylko z jednego powodu, a mianowicie id video się nie zgadza.
Patrz:
Chcę pobrać ten materiał
http://tvp.pl/pub/stat/videofileinfo?video_id=42549669
Ma on id 42549669 zatem strzelam do videofileinfo i w odpowiedzi uzyskuje prawdziwe id materiału z
`"copy_of_object_id": "42383664"`
W przypadku gdy nie będzie "copy_of_object_id" oznacza to, że id materiału jest takie jak w adresie url i nie ma potrzeby go zmieniać zatem można strzelić do tokenizera z id widocznego w url

**Comment by HerMajestyDrMona** [comment]
Hmm, faktycznie to videofileinfo rozwiązuje kwestie innych ID, bez potrzeby wyłączania adblocka itd. Czyli praktycznie oryginalne zapytanie z poprawnym ID i mamy materiał bez sprawdzania jsona w nowej karcie itd.

**Comment by zacny** [comment]
Wymyśliłem jak obejść CORS, ale moje rozwiązanie nie jest jeszcze gotowe. Skrypt się przez to nieco komplikuje, ale na przyszłość może się takie coś przydać.

**Comment by funplayertv** [comment]
@zacny zdradzisz rąbka najemnicy, jaki masz na to pomysł?

**Comment by HerMajestyDrMona** [comment]
@zacny, zwróć uwagę że videofileinfo działa na vod (i może innych) subdomenach. Tak więc nie sypie CORSa przy pobieraniu prawdziwego ID.

**Comment by zacny** [comment]
> @zacny zdradzisz rąbka najemnicy, jaki masz na to pomysł?

Eksperymentuję. 
Na razie zrobiłem coś co działa i ładnie wygląda nawet.
Otwiera się zakładka, ale zamiast zwykłego ajaxa i stworzenia dokumentu z linkami, tworzy się niewidzialny iframe na całą stronę z: https://www.vod.tvp.pl/pub/stat/videofileinfo?video_id=...
Tampermonkey ma include na ten adres i odpala się ponownie skrypt. Teraz można się dostać do zawartości iframe (z okna głównego jest to niemożliwe z przyczyn bezpieczeństwa).
Json zostaje przetworzony i wykrywam właściwe id.
Następuje stara procedura pobierania linków a jej rezultat zastępuje zawartość ramki.

Nie można wystać do tego videofileinfo normlanie ajaxa, też jest błąd cross-origin-access (chyba dlatego, że inna ścieżka).
Z uwagi na to, że jest to jednak w tej samej domenie, to wydaje mi się, że cały proces można uprościć. Przez zapisanie jsona w localstorage. I odczytanie go potem w poprzednim konktekście. Powinno działać nieco lepiej, bo nie muszę zgadywać czy załadował się json tylko będę to cyklicznie sprawdzał.
Niestety trick z localstorage nie zadziała dla innych domen.

**Comment by zacny** [comment]
@funplayertv 
@HerMajestyDrMona 
Znalazłem proste rozwiązanie, będzie można robić zapytania wszędzie bez żadnych właściwie ograniczeń. Autoryzacja - nie ma problemu, też jest możliwa.
Co to za rozwiązanie to na razie nie zdradzam, ale nie będzie potrzeba tego całego bełkotu co napisałem wyżej. Będzie prosto i przyjemnie.

**Comment by zacny** [comment]
@aleks365 @funplayertv @HerMajestyDrMona 
Dziękuję wszystkim za pomoc.
