### ISSUE TITLE
arte.tv - brak aktywnosci

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#32]
Hej!
z jakiegoś powodu, przestało mi działać... w ogole nie wykrywa / nie pojawia się guzik pobierz video.
czy ktoś moze to potwierdzić?

nie działajace przykładowwe linki:
https://www.arte.tv/pl/videos/088176-004-A/johnny-marr-na-festiwalu-cabaret-vert/

https://www.arte.tv/pl/videos/078162-003-A/nowosci-w-kardiologii/

https://www.arte.tv/pl/videos/060338-001-A/ermonela-jaho-w-traviacie/

wersja skryptu 5.12.0

**Comment by zacny** [comment]
Wczoraj to zauważyłem przy testach nowej wersji. Już mi się nie chciało poprawiać, bo stwierdziłem, że przecież nikt do jutra nie zauważy. A tu @funplayertv wziął i jak zwykle zauważył. Dobra robota. Jakieś zmiany na stronie zrobili i pozmieniały się urle.

**Comment by funplayertv** [comment]
> 
> 
> Wczoraj to zauważyłem przy testach nowej wersji. Już mi się nie chciało poprawiać, bo stwierdziłem, że przecież nikt do jutra nie zauważy. A tu @funplayertv wziął i jak zwykle zauważył. Dobra robota. Jakieś zmiany na stronie zrobili i pozmieniały się urle.

pozwole sobie zacytowac i podziekwoac za dobre słowa ;D. ot co po prostu jestem cuzjny :D a ze akurat potrzebowaęłm... to odkryłem tak jak i teraz ze dalej nie działa :(

**Comment by funplayertv** [comment]
Nowa zakładka wyswietla tylko czarny pasek pusty... jakby bez danych

**Comment by zacny** [comment]
Czyli zmiany są większe niż myślałem

**Comment by funplayertv** [comment]
na wyglada tak jakby json był pusty / bez źrodeł plikow :(

**Comment by zacny** [comment]
Tak jakby naprawiłem.

**Comment by funplayertv** [comment]
Zacny Panie @zacny, wygląda na to ze wszystko zacnie śmiga ^^

**Comment by zacny** [comment]
@funplayertv jeszcze mała popraweczka dla czystości kodu
