### ISSUE TITLE
Wsparcie dla napisów na Ipla.tv

### ISSUE THREAD

**Issue by sevospl** [zacny/voddownloader#33]
Cześć. Przede wszystkim dziękuję za Twoje napracowanie przy rozszerzeniu - oby tak dalej:)

Chciałbym prosić o wprowadzenie wsparcia dla pobierania napisów z Ipla.tv - napisy są dostępne przykładowo w serialu "Przyjaciółki". Z inspekcji strony w Chrome wynika, że wykorzystywany jest plik z końcówką .vtt.

**Comment by zacny** [comment]
Co to znaczy wsparcie? Czego oczekujesz?

**Comment by zacny** [comment]
@HerMajestyDrMona, @funplayer
Jak będziecie mieli chwilę to zobaczcie czy można się tam jakoś dobić, to można by zrobić np. przycisk napisy.

**Comment by funplayertv** [comment]
@zacny  wczoraj na szybko zerknąłem, jak na razie bez wniosków żadnych, jak coś wymysle/znajdę dam cynę :)

**Comment by HerMajestyDrMona** [comment]
Tak na szybko, z tego co widzę napisy są w źródle strony:
```
[{&q;src&q;:&q;http://redirector.redefine.pl/redb_subtitles/dbqmy943c48n637xf8jqtz73pwzmuyie.stl&q;,&q;format&q;:&q;stl&q;,&q;name&q;:&q;PL&q;,&q;isDefault&q;:false},{&q;src&q;:&q;http://redirector.redefine.pl/redb_subtitles/a5rt5kxq6f5q5dieqx77zjqu7esii4w7.srt&q;,&q;format&q;:&q;srt&q;,&q;name&q;:&q;PL&q;,&q;isDefault&q;:false},{&q;src&q;:&q;http://redirector.redefine.pl/redb_subtitles/4w6y4vqvrmi175v4zk7rxeeo85y5f676.vtt&q;,&q;format&q;:&q;vtt&q;,&q;name&q;:&q;PL&q;,&q;isDefault&q;:false}]}
```
Może by tak przeszukać po ".srt", potem indexBefore "http" / "https", potem string.length < LIMIT, inaczej szukaj kolejnej instancji .srt? Pobawię się z zapytaniem jeszcze później, wiadomo że byłaby to czystsza metoda.

**Comment by HerMajestyDrMona** [comment]
Zobacz proszę taki pseudo-kod ode mnie:
```
var GotCorrectSRT = false;
        var SRTURLFinal = "";
        var n = document.body.innerHTML.lastIndexOf(".srt");
        if(n > -1){
            var bodyUntilSRT = document.body.innerHTML.substr(0, n + 4);
            var n2 = bodyUntilSRT.lastIndexOf("http");
            if(n2 > -1){
              var SrtURLTemp = bodyUntilSRT.substr(n2);
              //http://redirector.redefine.pl/redb_subtitles/a5rt5kxq6f5q5dieqx77zjqu7esii4w7.srt
              if(SrtURLTemp.length > 80 && SrtURLTemp.length < 90){
                  GotCorrectSRT = true;
                  SRTURLFinal = SrtURLTemp;
                  //alert(SRTURLFinal);
              }
            }

        }

	    IPLA.grabVideoFormats = function(data){
	        var formats = [];
	        var vod = data.vod || {};
	        if(vod.copies && vod.copies.length > 0){
	            $.each(vod.copies, function( index, value ) {
	                formats.push(new Format({
	                    bitrate: value.bitrate,
	                    url: value.url,
	                    quality: value.quality_p
	                }));
	            });

                if(GotCorrectSRT){
                   //alert("correct srt");
                   formats.push(new Format({
	                    bitrate: "SRT",
	                    url: SRTURLFinal,
	                    quality: "Napisy SRT"
	                }));
                }
	            return {
	                title: vod.title,
	                formats: formats
	            }
	        }
	        throw new Exception(config.error.noSource, window.location.href);
	    };
```

**Comment by zacny** [comment]
@HerMajestyDrMona 
Na razie nie sprawdziłem, ale jak jest w źródłach to spoko. Pytanie czy dobrym pomysłem będzie dodanie przycisku z napisami. Może jakiś inny pomysł?

**Comment by HerMajestyDrMona** [comment]
Może nowa opcja pod "quality", zwana "type" i tutaj można użyć numerku lub "video", "subtitles". Jeśli subtitles, to pomijałoby wyświetlanie bitrate/rozdzielczości, a ikonka przy "otwórz" byłaby inna (jakiegoś papieru z tekstem czy coś)?

**Comment by zacny** [comment]
@HerMajestyDrMona Ja myślałem o 4 przycisku w linii wyników obok otwórz pobierz i kopiuj

**Comment by HerMajestyDrMona** [comment]
Tylko co wtedy? Przy wszystkich przyciskach ten sam link do napisów? Co jeśli chcielibyśny dodać wszystkie 3 dostępne formaty napisów (.srt, .stl .vtt), albo dla innych języków (jeśli by się pojawiły w jakimś serwisie)? Wtedy musiałby być 3 nowe przyciski lub więcej. Chyba warto listować je jak rozdzielczości materiałów. Ale to tylko moja opinia.

**Comment by zacny** [comment]
Pomyślę jak to zrobić. Najpierw muszę sprawdzić czy można je bez problemów pobierać ze źródła strony lub z posta, choć to pierwsze brzmi rozsadniej.

**Comment by HerMajestyDrMona** [comment]
> choć to pierwsze brzmi rozsadniej.

Z czasem i tak to pewnie zmienią. Ale być może "kupimy" trochę czasu żeby się teraz z tym nie męczyć.

**Comment by funplayertv** [comment]
jak dla mnie, dodatkowy przycisk:
![obraz](https://user-images.githubusercontent.com/50556762/63725371-71996180-c85a-11e9-870e-1a2d76715c08.png)

i w zależności od tego ile jest wersji napsiów - sub menu.

p.s. to tak tylko zaznacze ze na vod.pl tez sporo materiałow z napisami, ale tam gdzies miałem zachowany sposob jak pobeirac to jak znajde to wrzucie

**Comment by zacny** [comment]
@funplayertv podoba mi się

**Comment by funplayertv** [comment]
a jezeli chodzi o strzałke to taka bedzie lpesza: ▼ bo ta wyzej wyglada dziwacznie :D

**Comment by HerMajestyDrMona** [comment]
Tylko, że Sub Menu też musiałby mieć 3 przyciski dla każdego z formatu napisów (Zapisz, Kopiuj, Otwórz)? Bo może ktoś wkleja do jakiegoś pliku tekstowego lub programu, niekoniecznie chce pobrać na dysk.

**Comment by funplayertv** [comment]
imho napisy to coś do pobrania... czyli ja osobiscie ustawiłbym jako domyslna akcja pobieranie a link kopiowałbys prawomlaskiem myszki.

[Napisy  ▼]:
 - srt
 - txt
 - wtw.

po kliknieciu w txt np. pobiera, prawomlask koiujesz sobie ze standardowego menu przegladari linka i wklejasz tam gdzie sobie chcesz

taka jest moja wizja :)

**Comment by HerMajestyDrMona** [comment]
A jeśli dostępne będzie (w przyszłości) kilka rodzajów napisów (dla większej ilości języków)? To te submenu będzie nienaturalnie rozbudowane.

**Comment by funplayertv** [comment]
@zacny 
w vod.pl napisy sa normalnie w json:
        "subtitles": [
          {
            "id": "pl",
            "name": "Polski",
            "url": "https://ocdn.eu/video-workflow/subtitles/27131711-e954-486a-b3e3-f43c57a7d48f.1553076342.873196.srt"
          }

@HerMajestyDrMona 
wtedy moze cos takiego:
 - polskie
 - - - txt
 - - - srt
 - angielskie
- - - txt

itd. 
jakies zwijane rozwijane sub/menu ?

**Comment by HerMajestyDrMona** [comment]
@funplayertv, no właśnie, i wszystko to powtórzone np. 10 razy jeśli jest dostępne 10 bitrate. A tak po prostu napisy byłyby na liście, trudne do przegapienia przez inny tekst i ikonkę.

**Comment by funplayertv** [comment]
zawsze sie jescze mozna zastanowic nad formą:
![napisy](https://user-images.githubusercontent.com/50556762/63750514-e8ac1580-c8ad-11e9-89f1-2baf781e0a6a.png)

w formie textowej, łądnie wyrownanej i ostylowanej, zwijanej.... 

z załzoenia skoro napisy to osobny byt a nie link do plikow itd. miałoby to sens, domyslnie zwiniete wiec kto by nie był zianteresownay to by tam nawet nie zagladał....
i nie tzreba by powtarzac tej samej informacji w kazdej pozycji ze zrodłem

**Comment by zacny** [comment]
Dobrzy ludzie dajcie linki gdzie te napisy można znaleźć, ale tak ze 3 różne z poszczególnych serwisów, żebym miał jak testy zrobić.

**Comment by HerMajestyDrMona** [comment]
To na Ipli mamy:
https://www.ipla.tv/wideo/serial/Przyjaciolki/5001717/Sezon-13/5015678/Przyjaciolki-Odcinek-155/02eadd46a4148e0c26914a9837ddecb2
https://www.ipla.tv/wideo/serial/Slubna-goraczka/5002396/Slubna-goraczka-Odcinek-13/9ff7d0c27128661668820932c65db785
https://www.ipla.tv/wideo/serial/W-rytmie-serca/5011030/Sezon-4/5015702/W-rytmie-serca-Odcinek-52/5446db382e3fbc5344cbda2ec70f42ba

Vod TVP chyba nie ma.

Na vod.pl trzeba się logować, to może @funplayertv będzie pamiętać na których sprawdzał?

**Comment by zacny** [comment]
@HerMajestyDrMona już umiem robić strzały po ten napisy

**Comment by zacny** [comment]
> @zacny
> w vod.pl napisy sa normalnie w json:
> "subtitles": [
> {
> "id": "pl",
> "name": "Polski",
> "url": "https://ocdn.eu/video-workflow/subtitles/27131711-e954-486a-b3e3-f43c57a7d48f.1553076342.873196.srt"
> }
> 
> @HerMajestyDrMona
> wtedy moze cos takiego:
> 
>     * polskie
> 
>     * * * txt
> 
>     * * * srt
> 
>     * angielskie
> 
>     * * * txt
> 
> 
> itd.
> jakies zwijane rozwijane sub/menu ?

@funplayertv 
Którego meteriału tyczyła się ta uwaga? Znalazłem tylko napisy na materiałach z ipli tam udostępnionych. Z samego vod nic nie widzę. Możesz dać jakieś przykłady?

**Comment by zacny** [comment]
Napisy znalazłem na ipla i ipla przez vod i tam działają. Jak są gdzieś jeszcze to proszę o osobne zgłoszenie.
