### ISSUE TITLE
Wsparcie skryptami aplikacji youtube-dl

### ISSUE THREAD

**Issue by DajMiliona** [zacny/voddownloader#34]
Dzień dobry cześć. 
Było by wspaniale, wesprzeć skryptami aplikacje youtube-dl https://ytdl-org.github.io/youtube-dl/index.html

**Comment by HerMajestyDrMona** [comment]
W sensie jak wesprzeć? youtube-dl rejestruje jakiś protokół w systemie (np. youtubedl://), żeby można było wywołać lokalny program przez przeglądarkę? Pomijając to, z jakich serwisów VOD da się pobierać za pomocą youtube-dl?

**Comment by DajMiliona** [comment]
youtube-dl pozwala pobierac pliki wideo z roznych serwisów. Wrzucasz w trybie tekstowym link do strony a on pobieta film.  JA uzywam GUI dla pliku youtube-dl.exe (uzywam tego GUI) https://github.com/murrty/youtube-dl-gui Wrzucasz linka do strony z filmem i program jedzie. Pobiera w najlepszej wersji lub z wybranej. Pobiera fajnie z FB Twitera Liveleak i mase mase innych.

**Comment by HerMajestyDrMona** [comment]
Co to youtube-dl wiemy, ale o co pytasz w kwestii "wsparcia" przez ten skrypt? Youtube-dl rejestruje protokół umożliwiający wywołanie tego programu przez przeglądarkę czy jak?

**Comment by DajMiliona** [comment]
Nie mam pojecia.... To trzeba zapytać autorów. Jesli Ci to cos pomoze, to przegladarka nie musi byc odpalona aby pobrac materiał wideo tym programem.

**Comment by HerMajestyDrMona** [comment]
Ah, Tobie chodzi o to, żeby pomóc w rozwoju youtube-dl, a nie żeby integrować z tym skryptem wywołanie youtube-dl dla VODów z którymi ten skrypt sobie nie radzi.
Równie dobrze ktoś od nich może zrobić podgląd kodu tutaj i zintegrować. Chyba tak to powinno działać.
