### ISSUE TITLE
Dziwne sortowanie i dane bitrate na player.pl

### ISSUE THREAD

**Issue by HerMajestyDrMona** [zacny/voddownloader#35]
Przykładowy materiał:
https://player.pl/playerplus/seriale-online/sedzia-anna-maria-wesolowska-odcinki,145/odcinek-628,S01E628,5308

Screenshot:
https://i.imgur.com/XT4Hs6C.png

Nie wiem czy czasem przez to "Standard" jest przed "Bardzo wysoką" jakością.

**Comment by zacny** [comment]
A to tylko w tym materiale tak jest. Bo albo ktoś się pomylił, albo zmienili koncepcję nazewnictwa plików.

**Comment by HerMajestyDrMona** [comment]
Oh, wydawało mi się że wszędzie. Ja tylko to oglądam na Playerze :D

**Comment by zacny** [comment]
Przyjrzałem się temu. Sortowanie będzie sprytniejsze w następnej wersji. Postanowiłem też wyrzucić te bzdury dotyczące bitrate, bo jak się okazuje pliki są nazywane bardzo różnie i nie sposób zgadnąć, która cześć nazwy co oznacza.

**Comment by HerMajestyDrMona** [comment]
Dzięki!
