### ISSUE TITLE
vod.pl / brak napisaów

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#38]
na początek... rewelacja wersja 6.0, urlop minał a tu przychodze i taka niespodzianka, dobra robota!

a teraz... dla tego materiału:
https://vod.pl/filmy/chce-sie-zyc-audiodeskrypcja-online/ncm9e63
- napisy sie nie wyswietlaja - mimo ze sa dostepne w jsonie....

https://player-api.dreamlab.pl/?body[id]=367980.274815409&body[jsonrpc]=2.0&body[method]=get_asset_detail&body[params][ID_Publikacji]=367980.274815409&body[params][Service]=vod.onet.pl&content-type=application/jsonp&x-onet-app=player.front.onetapi.pl&callback=

dla tego tak samo:
https://vod.pl/filmy/barany-islandzka-opowiesc-napisy-dla-nieslyszacych/27trwj8

miłego! :)

**Comment by zacny** [comment]
Coś chyba źle sprawdziłeś :)
