### ISSUE TITLE
BB Arena nie działa

### ISSUE THREAD

**Issue by Rafu7s** [zacny/voddownloader#39]
Odcinek 2 nie działa na player.

**Comment by HerMajestyDrMona** [comment]
link?

**Comment by Rafu7s** [comment]
https://player.pl/big-brother/big-brother-arena-odcinki,17810/odcinek-2,S02E02,152305

**Comment by zacny** [comment]
@HerMajestyDrMona 
TVN chyba postawił na windows media player w swoich nowych materiałach. Chyba kogoś nieźle poniosła fantazja. Obciążenie serwerów to raczej sporo urośnie.

**Comment by funplayertv** [comment]
to samo chciałem zgłąszać... i o tym samym sobie pomyslałem, ze musza miec mocne serwery... swoja droga troche to utrudnia sprawe, bo teraz trzeba odtwarzac w firefoxie przez vlc... bo w wbudowanym sie nie da, chyba ze masz jakis patent? ale działac działa i odtwarza :)

**Comment by HerMajestyDrMona** [comment]
Oh, na slacku dyskutowaliśmy. Wygląda na to, że oni coś zmieniali i teraz przywracają jak było (używali src zamiast url). Np. na wersji 6.1 już działa zgłoszony materiał, ale tylko w wersji HD / SD. Poprawka została wprowadzona żeby używać obydwu form tak więc jak przywrócą tak jak było to nie będzie przeszkadzać.

**Comment by zacny** [comment]
@funplayertv raczej można skonfigurować przeglądarkę żeby odtwarzała ten format - na windowsie - na linuksie mi się na razie nie udało, ale nie chciało mi szukać i olołem. wvm do sieci z tego co wiem nadaje się ... słabo. Z drugiej strony w niektórych częściach świata domu budują z krowiej kupy i sobie chwalą. Może tvn wie lepiej.

**Comment by Rafu7s** [comment]
Zaktualizowałem, ale nadal nie wiem jak ściągnąć. Jak dam pobierz, to nic nie pobiera, a jak dam otwórz i sciagne ten plik *.wmv i otworzę to tylko pierwsze minuty działają.

**Comment by funplayertv** [comment]
@zacny @HerMajestyDrMona wygląda na to tak jak pisze @Rafu7s  ze co prawda dostep do plikow jestm ale maja DRM i stad tylko kilka minut mozna odpalic...

**Comment by zacny** [comment]
@HerMajestyDrMona @funplayertv 
Może tak być porównajcie te dwie wartości z jsonów:
video_content_license_type
video_content_licenserenew_url
https://player.pl/api/?platform=ConnectedTV&terminal=Panasonic&format=json&authKey=064fda5ab26dc1dd936f5c6e84b7d3c2&v=3.1&m=getItem&id=152305
https://player.pl/api/?platform=ConnectedTV&terminal=Panasonic&format=json&authKey=064fda5ab26dc1dd936f5c6e84b7d3c2&v=3.1&m=getItem&id=146182

**Comment by funplayertv** [comment]
a zapytam, bo nie pamietam czy ten temat był badany itd.

w źródłach wtyczki do KODI jest cos takiego:

```
platform = {
     'Panasonic': {
        'platform' : 'ConnectedTV',
        'terminal' : 'Panasonic',
        'authKey' : '064fda5ab26dc1dd936f5c6e84b7d3c2',
        'host' : 'Mozilla/5.0 (Linux; U; Android 2.3.4; en-us; Kindle Fire Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',
        'api' : '3.1',
        'fallback' : 'Android'
    },   
    'Samsung': {
        'platform' : 'ConnectedTV',
        'terminal' : 'Samsung2',
        'authKey' : '453198a80ccc99e8485794789292f061',
        'host' : 'Mozilla/5.0 (SmartHub; SMART-TV; U; Linux/SmartTV; Maple2012) AppleWebKit/534.7 (KHTML, like Gecko) SmartTV Safari/534.7',
        'api' : '3.6',
        'fallback' : 'Android'
    },
    'Android': {
        'platform' : 'Mobile',
        'terminal' : 'Android',
        'authKey' : 'b4bc971840de63d105b3166403aa1bea',
        'host' : 'Apache-HttpClient/UNAVAILABLE (java 1.4)',
        'api' : '3.0',
        'fallback' : 'Android2'
    },
    'Android2': {
        'platform' : 'Mobile',
        'terminal' : 'Android',
        'authKey' : 'b4bc971840de63d105b3166403aa1bea',
        'host' : 'Apache-HttpClient/UNAVAILABLE (java 1.4)',
        'api' : '2.0',
        'fallback' : 'Android3'
    },
    'Android3': {
        'platform' : 'Mobile',
        'terminal' : 'Android',
        'authKey' : '4dc7b4f711fb9f3d53919ef94c23890c',
        'host' : 'Player/3.3.4 tablet Android/4.1.1 net/wifi',
        'api' : '3.1',
        'fallback' : ''
    },    
}
```

tutaj we wtyczce uzywamy panasonica, moze do innych 'platform' sa dostepne bez DRM ?

**Comment by zacny** [comment]
@funplayertv 
O bardzo cenna informacja, sprawdzę to w wolnej chwili. Dzięki.

**Comment by zacny** [comment]
@funplayertv dwa pierwsze działają po zmianie api na v + kilka innych parametrów typu format i id, ale zwraca to samo.

**Comment by funplayertv** [comment]
to cos czuje, ze nowe materiały sa tylko takie i chyba nic z tym na chwile obecna zrobić sie nie bedzie dało? chyba ze jak ktoś ma jakies smart TV i jest w stanie zrobić jakis sniiffing i pobadac pakiety co tam leci, bo moze teraz mp4 pobierane jest inbaczej. @zacny @HerMajestyDrMona  co sadzicie?

**Comment by zacny** [comment]
@funplayertv 
Obecna wersja pokazuje informację, że taki materiał jest niedostępny, ale nie wiem czy dobrze zrobiłem taki warunek:
`main.video_content_license_type !== 'WIDEVINE'`

**Comment by funplayertv** [comment]
@zacny obadałem... teraz faktycznie pojawia sie stosowny komunikat, taka ciekawsotka, ostatni odcinek kuby z gesslerowa tez był wczoraj tylko z widvine, dzis juz działa normlanie, sprawdizłem tez ten odcinek BB arena z tego watku ale nistety tutaj dalej widvine ale jzu opisany stosonym komunikatem z wersji 6.3.1 :)

moze ktos bedzie miał sposob na to moze istnieje, ale chyba musimy poczekac, bo ja osobiscie pomysłu nie mam zadnego.
