### ISSUE TITLE
brak css'a

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#4]
szybka akcja i pewnie pomyłka przypadkowa....

https://raw.githubusercontent.com/zacny/voddownloader/master/voddownloader.css - 404 a taki adres jest w skrypcie....

po zmianie recznej na 

https://raw.githubusercontent.com/zacny/voddownloader/master/dist/voddownloader.css

smiga ;)

**Comment by HerMajestyDrMona** [comment]
Greasyfork nie może pobrać najnowszej wersji z githuba:

Script sync failed - @description:pl must not be the same as name.

Zaraz poprawię.
