### ISSUE TITLE
player już nie działa

### ISSUE THREAD

**Issue by swdefghjfr4rfv** [zacny/voddownloader#40]
Dzisiaj nie wyskakują opcje z jakościami do pobrania, jest tylko hd i sd ale nie reagują i nie pobiera się film

**Comment by marcinek1992** [comment]
Link:
https://player.pl/programy-online/kuba-wojewodzki-odcinki,455
Komunikat:
Nie udało się odnaleźć idetyfikatora.
Algorytm rozpoznawania identyfikatora wideo na stronie: https://player.pl/programy-online/kuba-wojewodzki-odcinki,455 zakończył się niepowodzeniem.
Jeżeli jest to główna strona programu oznacza to, że nie udało się odnaleźć identyfikatora ostatniego odcinka. Wejdź na stronę odcinka i spróbuj ponownie.
Może to również oznaczać błąd skryptu.
Informacje o systemie: Chrome 76.0.3809.132 on Windows 10 64-bit
Wersja pluginu: 4.8.41

**Comment by marcinek1992** [comment]
> Już zgłoszone. Możesz dopisać tam link, który Ci nie działa.

U góry dodałem. Z góry dziękuje za naprawienie błędu. Na mam talent też występuje niestety :(

**Comment by zacny** [comment]
@marcinek1992 
Przytoczony komunikat nie jest błędem. Należy jedynie przeczytać go ze zrozumieniem.
Natomiast np. ten odcinek:
https://player.pl/programy-online/kuba-wojewodzki-odcinki,455/odcinek-4,S27E04,150574
jest najprawdopodobniej źle przygotowany w wyniku jakiś błędów w serwisie, na co również skrypt wpływu nie ma. Pewnie naprawią za jakiś czas.

**Comment by marcinek1992** [comment]
> @marcinek1992
> Przytoczony komunikat nie jest błędem. Należy jedynie przeczytać go ze zrozumieniem.
> Natomiast np. ten odcinek:
> https://player.pl/programy-online/kuba-wojewodzki-odcinki,455/odcinek-4,S27E04,150574
> jest najprawdopodobniej źle przygotowany w wyniku jakiś błędów w serwisie, na co również skrypt wpływu nie ma. Pewnie naprawią za jakiś czas.

Robisz super robotę ale niestety chyba Player.pl coś pozmieniał bo nic nie mogę wygenerować i ściągnąć :(

**Comment by zacny** [comment]
@marcinek1992 Materiał wyświetla mi się już bez problemów.
