### ISSUE TITLE
vod ipla

### ISSUE THREAD

**Issue by zacny** [zacny/voddownloader#41]
Zmiany w serwisie spowodowały, że w tym kontekście są jakieś problemy. Przykładowy link:
https://vod.pl/filmy/vabank/mmwldxr
Przykładowy materiał nie posiada najprawdopodobniej źródeł mp4.

**Comment by zacny** [comment]
@HerMajestyDrMona 
@funplayertv
To źródło wymaga innej obsługi. Posiada inny iframe, ale to nie jest największy problem. Również pobieranie id trzeba zrealizować w inny sposób. Trzeba poszukać w iframe:
`partner.ipla.tv`
elementu
`<script>`
W środku jest funkcja z mediaId:
`function loadParams(){
  return {
    mediaId: "a2eb25233398b9de123435705ce2fc89",
    playerDataUrl: "https://distro.redefine.pl/partner_api/v1/2yRS5K/media/MEDIA_ID/vod/player_data",
    playbackQueueUrl: "https://distro.redefine.pl/partner_api/v1/2yRS5K/media/MEDIA_ID/vod/next_media",
    portalCode: "onet",
    autoplay: false
  }
}`

A potem trzeba uderzyć po dane tak:
`https://distro.redefine.pl/partner_api/v1/2yRS5K/media/a2eb25233398b9de123435705ce2fc89/vod/player_data?dev=pc&os=linux&player=html&app=firefox&build=12345`
Niestety brak jest strumieni w mp4. Same mpd.
Sprawdziłem też, że na starszych materiałach można użyć tego samego api i tutaj już zwraca mp4. Oto przykład:
`https://distro.redefine.pl/partner_api/v1/2yRS5K/media/02eadd46a4148e0c26914a9837ddecb2/vod/player_data?dev=pc&os=linux&player=html&app=firefox&build=12345`
Na razie nie mam pomysłu co zrobić z tym fantem. Jeżeli znajdziecie więcej takich materiałów to dajcie znać, bo muszę wykonać więcej testów.
Być może można w te api strzelić z innymi parametrami, czego rezultatem będzie też inna lista strumieni.

**Comment by HerMajestyDrMona** [comment]
Ogólnie wszystkie materiały co na vod.pl są też na Ipli.
https://www.ipla.tv/wideo/film/Vabank/a2eb25233398b9de123435705ce2fc89

No i w tym wypadku też niczego nie zwraca.

.mpd to patent jak na tym niewspieranym serwisie playpuls, czy jak to się nazywało. Można pobrać youtube-dl, jeśli nie ma innego DRM.

Ipla chyba nie wprowadziła żadnej zmiany, że nie ma mp4 do nowych materiałów, bo np. takie Ekhemmmmmmmmmmmm:
https://www.ipla.tv/wideo/serial/Pierwsza-milosc/828/Odcinki-2501-3000/5010718/Pierwsza-Milosc-Odcinek-2921/176acdb671964c356a325fd6f645621f
Ma dalej źródła w mp4.

**Comment by zacny** [comment]
@HerMajestyDrMona 
Przydałoby się jednak wyświetlać i tu i tam to samo, a na razie tak nie jest. Trzeba więc to ujednolicić. Jeżeli też ten strzał do api działa w obu przypadkach co sprawdzę to pewnie trzeba by właśnie tak pytać o dane.

**Comment by zacny** [comment]
Dużo przykładów do nowego przypadku:
https://vod.pl/klasyka-polskiego-kina

**Comment by jankesikkk** [comment]
Witaj
Mam problem na player.pl otoż nie moge pobrać programów które własnie teraz maja 2 sezon i odcinki sa emitowane
Np. https://player.pl/playerplus/programy-online/klimek-kontra-duda-odcinki,17821/odcinek-2,S02E02,152735

**Comment by funplayertv** [comment]
> 
> 
> Witaj
> Mam problem na player.pl otoż nie moge pobrać programów które własnie teraz maja 2 sezon i odcinki sa emitowane
> Np. https://player.pl/playerplus/programy-online/klimek-kontra-duda-odcinki,17821/odcinek-2,S02E02,152735

bo są niedostepne, odcinek 1 widze jest ok, ten ktory pokazałes jest przeznacozny tylko dla abonamentu i nie ma legalnego sposoby aby go obejrzec ;)

**Comment by jankesikkk** [comment]
a po czym widzisz że jest dostępny żeby pobrać? i czy jest jakiś czas po którym są one dostępne?

**Comment by zacny** [comment]
@jankesikkk nie wrzucamy w jeden temat innego. W przyszłości będę takie coś od razu usuwał. Jak nie masz pewności, że coś jest błędem to spytaj na forum, o tu:
https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod/feedback

**Comment by jankesikkk** [comment]
Dzięki i sorry za zaśmiecenie tematu....

**Comment by funplayertv** [comment]
@zacny tylko dopytam, jak sprawdzałes, to znalazłes jakikolwiek materiał ktory wyswietla mp4 ? czy tylko samo mpd ? bo z ciekawosci zerknałem i t ktore sprawdzałem z linka Twojego to pokazuje bład ze nie ma źrodeł... 

p.s. myslałem moze tez nad tym, aby rodzdzielić/dodać nowy komunikat informujacy o tym, ze brak źrodeł w formacie mp4 co uniemozliwia odtwarzanie itd. ?

bo z tego co widze wykrywamy czy jest drm - ok, ale jak nie ma drm i nie ma *.mp4 to moze w komunikacie informujacym o tym ze brak źrodeł dopisac, ze wynika to z powodu tego ze zrodła sa w innym formacie niz mp4 co uniemozliwia działanie bl,alablbal, co sadzicie ?

**Comment by zacny** [comment]
@funplayertv tam nie ma mp4 tylko mpd. Mają dodatkowe zabezpieczenie i strumieniowany jest oddzielnie dźwięk, a oddzielnie obraz.
