### ISSUE TITLE
Player tvn

### ISSUE THREAD

**Issue by wocek** [zacny/voddownloader#42]
Nie działa.

**Comment by zacny** [comment]
Ręce i nie tylko ręce opadają.

**Comment by wocek** [comment]
Skoro jesteś autorem skryptu, to mógłbyś zbadać przyczynę... Po coś się tym zająłeś.

**Comment by zacny** [comment]
Jak już zgłaszasz błąd to też mógłbyś doczytać jak to się robi, bo najwyraźniej nie masz w tym dużego doświadczenia. Zgłosisz jak należy, to będę miał szansę się tym zająć.
