### ISSUE TITLE
Problemy ze ściąganiem

### ISSUE THREAD

**Issue by venor900** [zacny/voddownloader#43]
Od 1 października mam problem ze ściąganiem "Faktów" z playera. Sciąga się tylko króciótki plik z komentarzem "Niepowodzenie-Zabroniony". Dotychczas nie było żadnych problemów. Wykonałem pobranie innego programu z playera i było o.k. Proszę o pomoc.

**Comment by zacny** [comment]
Link poproszę.

**Comment by venor900** [comment]
https://player.pl/programy-online/fakty-odcinki,516/odcinek-7946,S28E7946,152851

**Comment by zacny** [comment]
Widzę, że starsze odcinki działają, te do końca września. Nie mam pomysłu dlaczego tak się dzieje. Możliwe, że to jakiś błąd lub niedopatrzenie opiekuna serwisu. Nowe materiały zachowują się jakby nie otrzymały wszystkich potrzebnych parametrów, ale tak nie jest. Trzeba poczekać kilka dni i zobaczyć czy coś się zmieni. Możliwe też, że nowo wypuszczone materiały mają jakieś inne zabezpieczenia, które po kilku dniach przestają obowiązywać. Player zrobił chyba ostatnio jakieś takie dziwne zmiany.

**Comment by venor900** [comment]
Dziękuję uprzejmie! Pozdrawiam :)

**Comment by zacny** [comment]
@venor900 
Sprawdziłem, że nowe odcinki są dostępne w mojej aplikacji w telewizorze. Niestety nie wiem, czy posiadają inne zabezpieczenia. Możliwe jest zapewne podsłuchanie ruchu między aplikacją i serwerem, by ustalić czy zmieniono sposób komunikacji. Muszę jednak się w tym kierunku najpierw dokształcić lub wpaść na inny pomysł.

**Comment by funplayertv** [comment]
hmm... @zacny patrząc na link wyzej to do każdego u mnie osobiście pokazują sie linki, natomiast nie ma możliwości otworzenia bo pojawia się 403. o tym własnie mowicie?

co do podsłuchu ruchu, moze jakies custom oprogoramowanie do routera i serwer proxy coby przez niego wszystko leciało, a Ty wtedy zerkniesz w pakiety ?

**Comment by zacny** [comment]
@funplayertv tak właśnie o tym

**Comment by cepter888** [comment]
hej ... fajnie ze sie przygladacie juz temu tematowi, osobiscie bardzo ubolewam na tym ze nie mozna aktualnych faktow ogladac, mecze sie teraz na kompie z reklamami ;)

**Comment by funplayertv** [comment]
@zacny albo ktoś inny z smart tv, patrzyłes moze na ten serwer proxy ? Dzis wpadło mi w rece narzedzie takie jak Burp, tak po krotce wydaje mi się ze mogłoby sie nadac do analizy, jako mostek miedzy TV a kompem i serwerem...

**Comment by zacny** [comment]
@funplayertv sprawdzałem jedynie dość dogłębnie ruch sieciowy w przeglądarce, ale tutaj nie jest używane api tylko materiały są ciągnięte ze strumienia. Na zabawy ze smart tv nie mam za bardzo czasu. Widziałem też, że plugin do kodi ma taki sam problem :)

**Comment by zacny** [comment]
@venor900 Wygląda na to, że fakty zaczęły na powrót działać. Proszę o potwierdzenie i zamknięcie błędu.

**Comment by venor900** [comment]
Potwierdzam-fakty działają!!! Można zamknąć temat.
