### ISSUE TITLE
Nie da się pobierać najnowszych materiałów na player.pl

### ISSUE THREAD

**Issue by Cisek25** [zacny/voddownloader#44]
Witam, od kilku tygodni występuje takie problem, że gdy jakiś materiał na player.pl jest nowy to przy próbie pobrania wyskakuje "Nie udało się odnaleźć źródeł do materiału.". Nie wiem czy ma to może związek z tym, że materiał jest na głównej stronie? Pozdrawiam

**Comment by zacny** [comment]
Tak było już zgłaszone:
https://github.com/zacny/voddownloader/issues/39
Wygląda na to, że po zmianach w serwisie odcinki premierowe są przez jakiś czas odpłatne.
Poproszę o przykładowy link to sprawdzę, jeszcze jak to jest na innych platformach np. tv
Obawiam się jednak, że nie da się nic z tym zrobić.
