### ISSUE TITLE
Drobne uwagi

### ISSUE THREAD

**Issue by blocker999** [zacny/voddownloader#45]
Na serialu " komisarz alex " brak info o rozdzielczości danych plików i brak w nazwie który to sezon np tu: https://vod.tvp.pl/video/komisarz-alex,odc-153-bardzo-dlugi-dzien,44083225

a zkolei w rytmie serca : https://www.ipla.tv/wideo/serial/W-rytmie-serca/5011030/Sezon-4/5015702/W-rytmie-serca-Odcinek-52/5446db382e3fbc5344cbda2ec70f42ba?seasonId=5015702 jest info o rozdzielczości ale brak info o sezonie 

no i w " o mnie się niemart ": https://vod.tvp.pl/video/o-mnie-sie-nie-martw,odc-3xi,44275051 jest kosmos bo na początek zgadujemy rozdzielczzość ( bo jest samo bitrate ) a po pobraniu, sortujemy i podpisujemy ręcznie bo niby pisze który sezon ale brak numeru odcinka ( to tylko 13 odcinków ).

Na koniec spojrzałem na player,a tu jeszcze inaczej, na warsztat wziełem serial " kryminalni " : https://player.pl/seriale-online/kryminalni-odcinki,6/odcinek-1,S01E01,101
to tak : brak bitrate jest rozdzielczość ale opisana słownie a nie tak jak na ipli cyframi a opis sezonu i odcinka jest tak zaawanowany że trzeba zgadywać. 

Ja poprostu chciałbym takich poprawek co dodadzą pełny opis pliku do pobrania jak ujednolicą podpis pliku.

**Comment by zacny** [comment]
1. https://vod.tvp.pl/video/komisarz-alex,odc-153-bardzo-dlugi-dzien,44083225
W pliku z danymi nie ma informacji o sezonie, ani informacji o rozdzielczości informacje o rozdzielczości w odtwarzaczu ni jak się mają do informacji z pliku danych. Widać, że nawet ilość źródeł jest zupełnie inna. Sortujemy po jedynej informacji jaką tam posiadamy, czyli po bitrate. Informacje o tytule można by w sumie przeczytać z htmla, ale trochę to słabe, skoro różni się od danych, tzn że mogą być sytuacje odwrotne w htmlu będzie jakiś mniej poprawny tytuł a w danych dobry.
2. https://www.ipla.tv/wideo/serial/W-rytmie-serca/5011030/Sezon-4/5015702/W-rytmie-serca-Odcinek-52/5446db382e3fbc5344cbda2ec70f42ba?seasonId=5015702
Tu w zasadzie można dorobić informację o sezonie jest naprzykład w:
related_title
Problem jednak jest taki, że raz w tym miejscu jest informacja o sezonie, innym razem coś innego. 

3. https://vod.tvp.pl/video/o-mnie-sie-nie-martw,odc-3xi,44275051
Nic nie trzeba zgadywać sortowanie jest po bitrate im większe tym lepsza jakość.
Arabskie cyfy - numer odcinka, rzymskie sezon. Tak sobie ktoś wymyślił.

4. https://player.pl/seriale-online/kryminalni-odcinki,6/odcinek-1,S01E01,101
Tutaj faktycznie można dodać chyba tytuły poszczególnych odcinków, bo taka informacja jest w danych. Konwencja nazewnictwa wzięta z portalu więc moim zdaniem adekwatnie.

> Ja poprostu chciałbym takich poprawek co dodadzą pełny opis pliku do pobrania jak ujednolicą podpis pliku.

To musisz uzgodnić sobie to z poszczególnymi portalami. Widzisz nie chcą współpracować, a nawet życie utrudniają ciągłymi zmianami. Niestety bez tych ustaleń skrypt będzie posiłkował się informacjami jakie dany portal udostępnia i będzie wyświetlał te rzeczy w rozmaity sposób.

**Comment by zacny** [comment]
@blocker999 być może z Twoich uwag jest coś do poprawienia, nie zamykaj tego na razie. Zastanowię się też czy sensowne jest przemapowanie opisów materiałów na jakieś inne, czytelniejsze.

**Comment by zacny** [comment]
@blocker999 w nowej wersji zrobiłem słownik, który ujednolica opisy materiałów. Po części jest to zgadywanie, ale chyba i tak lepiej niż było.
