### ISSUE TITLE
player 4k - nie mozna pobrac

### ISSUE THREAD

**Issue by cepter888** [zacny/voddownloader#48]
Witam,

czy istnieje mozliwosc sprawdzenia czemu materialow 4k nie mozna sciagnac?

przyklad:
https://player.pl/seriale-online/39-i-pol-tygodnia-odcinki,20899/odcinek-7,S01E07,151539

**Comment by zacny** [comment]
Dla podanego materiału nie jest zwracany plik z danymi. 
Istnieją następujące możliwości:

1. Zostały dodane kolejne zabezpieczenia i zostanie to trwale zablokowane.
2. Materiał został w jakiś sposób źle umieszczony w serwisie i ktoś to za jakiś czas poprawi (takich sytuacji było już na pęczki.
3. Nowe odcinki/seriale są czasami na pewien czas blokowane, by potem stać się ogólnodostępne.

Która z tym możliwości tym razem - czas pokaże.

**Comment by zacny** [comment]
Dobra wygląda na to, że ten materiał stał się płatny. Skrypt umożliwia tylko oglądanie materiałów ogólnodostępnych.
