### ISSUE TITLE
Nie udało się odnaleźć źródeł do materiału.

### ISSUE THREAD

**Issue by lemieevil** [zacny/voddownloader#49]
Witam, pobrałem dziś Skrypt umożliwiający pobieranie materiałów ze znanych serwisów VOD. wersja Wersja 6.6.2 jednak przy pobieraniu materiału z player+ a mianowicie https://player.pl/seriale-online/chylka-odcinki,15976/odcinek-4,S02E04,155585 wyskoczył mi błąd taki jak w temacie. Czy jest jakaś szansa na pobieranie takich materiałów z tej strony?

P.S Nie wiem jak to nazwać, ale swego czasu natrafiłem na taką stronę jak polishsource i widziałem, że tam wstawiają takie odcinki na których ja mam błąd pobierania :/ Jeżeli jest jakikolwiek sposób (nawet płatny) to proszę o pomoc.
Pozdrawiam.

**Comment by HerMajestyDrMona** [comment]
To jest płatny materiał i nawet według opisu nie ma prawa działać: https://greasyfork.org/en/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod

**Comment by zacny** [comment]
Skrypt z założenia umożliwia oglądanie materiałów bez reklam, a nie ich kradzież.
