### ISSUE TITLE
ipla - dostepnosc na platformach

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#52]
hej @zacny szybka akcja, niekotre materiały na ipla, zdarzają się być dostepne tylko np, za pomocą:

http://getmedia.redefine.pl/vods/get_vod/?cpid=1&ua=mipla_ios/122&media_id=5359b1a31e106c4337e9c0a4e4448b47

skrypt generuje:
https://getmedia.redefine.pl/vods/get_vod/?cpid=1&ua=www_iplatv_html5/12345&media_id=828

i tutaj w tym konkretnym przypadku i czasami w innych jest 404... a wyzej nie :)

**Comment by zacny** [comment]
Ale ten materiał akurat działa. 
https://getmedia.redefine.pl/vods/get_vod/?cpid=1&ua=www_iplatv_html5/12345&media_id=5359b1a31e106c4337e9c0a4e4448b47
Znajdź przypadek, że faktycznie jest tak jak mówisz, a nie wklejasz mi tutaj jakieś wadliwe urle. 
Ślepo zawierzyłem, zrobiłem już rozkminę jak to dodać nawet, po czym sprawdzam i ... nie ma przypadku testowego.

**Comment by funplayertv** [comment]
@zacny Drogi Kolego, przepraszam jezeli wprowadziłem zamieszanie, ale jestem ostania osoba, która nie weryfikuje tego o czym potem ma truć tyłek :), pozwolę sobie raz jescze napisac o co chodz.

otoż... po kolei:
sytuacja wyglądała następująco i juz pare razy sie z tym spotkałem, ale z racji na to ze nie jest to jakis bug fatal error to odpuszczałem temat...

np. materiał taki jak:
https://www.ipla.tv/wideo/serial/Pierwsza-milosc/828/Odcinki-2501-3000/5010718/Pierwsza-Milosc-Odcinek-2974/5359b1a31e106c4337e9c0a4e4448b47?seasonId=5010718 z reguły dostepny po godiznie 18, albo niewiele po.

obecnie tak jak twieerdzisz i masz racje skrypt pobiera juz dane (widocznie to sie zmienia z biegiem czasu) ale na poczatku po godiznie 18 kiedy materiał zaczal byc dostepny zdarza sie ze skrypt wyswietla ze jest brak materiału... 

ale proba wyciagniecia go za pomoca platformy ios z linka mipla_ios przynosi efekt, z ta roznica ze materiał wteyd tlyko 720p jest dostepny.

nie wiem czy ma tu wpływ tez to w jaki sposob został wczoraj wygenerowany adres bowiem, wczoraj adres wygenerowany przez skrypt z pierwszego postu:

https://getmedia.redefine.pl/vods/get_vod/?cpid=1&ua=www_iplatv_html5/12345&media_id=828

nadal ma 404 i wczoraj tez nie działał

dzis skrypt juz generuje adres:

https://getmedia.redefine.pl/vods/get_vod/?cpid=1&ua=www_iplatv_html5/12345&media_id=5359b1a31e106c4337e9c0a4e4448b47

moze fkatrycznie te wszytskie błedy wyniakaja z platformy i ona ma bugi w sobie, ale nei wiem nie mam pomysłu jak to zweryfikowac teraz

**Comment by funplayertv** [comment]
o. przykład kolejny:
https://www.ipla.tv/wideo/serial/Rolnicy-Podlasie/5017276/Sezon-1/5017277/Rolnicy-Podlasie-Odcinek-7/6a5a81ceb3d68657d08673b15a65be3d

skrypt nie wyswietla linku ( generuje: https://getmedia.redefine.pl/vods/get_vod/?cpid=1&ua=www_iplatv_html5/12345&media_id=6a5a81ceb3d68657d08673b15a65be3d ), 


ale za pomocą 

http://getmedia.redefine.pl/vods/get_vod/?cpid=1&ua=mipla_ios/122&media_id=6a5a81ceb3d68657d08673b15a65be3d

mozna uzyskac 720p

**Comment by zacny** [comment]
Myślałem, że wkleiłeś coś innego niż miałeś zamiar.
Faktycznie ten przykład działa jak na razie. Myślę, że wystawiają za wcześnie, jak nie jest jeszcze wszystko gotowe. Jednak jeżeli ten przykład się utrzyma, to spróbuję zaimplementować rozwiązanie, które do tego wymyśliłem. Rozumiem, że tak mają niektóre meteriały, które są "bardzo świeże"?

**Comment by funplayertv** [comment]
tak, z mojego doświadczenia do tej pory wynika, ze akurat MNIE spotkały takei materiały, które własnie jako świeże nie były dostepne, ale niestety nie moge dac sobie odciąc reki i zapewewnić ze nie dzieje sie tak z materiałami innymi...

**Comment by funplayertv** [comment]
kolejny przykład zaczerpniety z forum: 
https://www.ipla.tv/wideo/film/Sliwowica/f92ae9f82c44835912bdd4aa9bdd762d 

skryptem nienada, przez mipla_ios działa ale jak w kazdym innnym przypadku masz 720p

**Comment by zacny** [comment]
To jest jakieś wadliwe, linków nie da się otworzyć:
https://www.ipla.tv/wideo/film/Sliwowica/f92ae9f82c44835912bdd4aa9bdd762d

**Comment by zacny** [comment]
Dobra problem rozwiązany.
