### ISSUE TITLE
strumien subtitles w vod.tvp.pl

### ISSUE THREAD

**Issue by TeleSmsng** [zacny/voddownloader#54]
Nie wiem czy juz ktos zglaszal, ale np. w Zmiennicy na cyfrowa.tvp.pl pojawia sie strumien napisy - opis: pl-PL, format: ttml - ale po kliknieciu w pobierz wyskakuje tylko komunikat Rozpoczęto pobieranie pliku ale nic sie nie dzieje.

**Comment by zacny** [comment]
Poczytaj jak dodać dziwaczne rozszerzenia do pobierania:
https://greasyfork.org/pl/forum/discussion/58432/changelog/p2
