### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by stancelkonrad** [zacny/voddownloader#55]
Niektóre odcinki programów otwierają się dobrze, a niektóre pomimo tego, że pokazują możliwe wersje do obejrzenia/pobrania nie można pobrać, a przy próbie obejrzenia pokazuje:
"Forbidden You don't have permission to access this resource. Apache Server at n-5-14.dcs.redcdn.pl Port 80"

Przykład:
Dieta czy cud
- odc.1 wszystko poprawnie,
- odc.2 forbidden

**Comment by zacny** [comment]
Wygląda jakby były źle nadane uprawnienia do plików. Pewnie wynika to z tego, że kolejne odcinki tego cuda są płatne, a uprawnienia nie zostały zmienione dla odcinków już dostępnych. Skrypt tego sam nie naprawi.

**Comment by stancelkonrad** [comment]
No właśnie sęk w tym, że odc. 2 i 3 są bezpłatne. Dopiero 4 i następne są płatne. Dzięki za odpowiedź :-)

**Comment by zacny** [comment]
Sprawdziłem. Teraz można pobrać.

**Comment by stancelkonrad** [comment]
Dzięki. Wszystko działa :-)
