### ISSUE TITLE
prośba o kontakt

### ISSUE THREAD

**Issue by Berbeloch** [zacny/voddownloader#56]
Siemanko Zacny!

Jest jakaś możliwość kontaktu z Tobą. Mam ze dwa pytania i obiecuję że jakoś się namacalnie odwdzięczę za pomoc!!!

**Comment by zacny** [comment]
Tutaj jest forum odnośnie tematu:
https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod/feedback
Moje konto:
https://greasyfork.org/pl/users/196944-zacny
Można prowadzić prywatne rozmowy.
