### ISSUE TITLE
Problem z player.pl

### ISSUE THREAD

**Issue by Majkovsky** [zacny/voddownloader#57]
**Może to oznaczać, że nie jest on publicznie dostępny, dostępne źródła nie mogą zostać wyświetlone w przeglądarce bez dodatkowego oprogramowania lub jest umieszczony w płatnej strefie.**

Nie można pobrać prapremier, z wykupionym wcześniejszym dostępem, proszę o pomoc.

**Comment by zacny** [comment]
Brzymi jak jakiś dostęp płatny. Skrypt wspiera tylko darmowe materiały. Ma na celu głównie umożliwić pominięcie oglądania uciążliwych reklam.

**Comment by Majkovsky** [comment]
Od reklam służy mi Nano Defender. Problem polega na tym, że odcinki po premierze można pobierać, lecz przedpremiery już nie. Dla przykładu - https://player.pl/playerplus/programy-online/ostre-ciecie-odcinki,1308/odcinek-4,S10E04,167253

Może jest możliwa zmiana w skrypcie, aby też można było pobierać odcinki prapremierowe.

**Comment by zacny** [comment]
Nie mam wykupionego konta na tym portalu, więc nawet nie mam jak tego sprawdzić.

**Comment by Majkovsky** [comment]
Mogę podać kod źródłowy lub cokolwiek, aby przetestować zmiany. Konto kosztuje tylko 5 zł za dostęp miesięczny.

**Comment by zacny** [comment]
To jest skrypt darmowy i można nim obsłużyć tylko materiały darmowe, inaczej naruszałby prawa autorskie. Skoro jest darmowy to znaczy, że tworzony jest bez środków finansowych, więc nie będę poświęcał swoich środków, nawet jeżeli to tylko 5 zł. Poza tym jak na wszystko potrzeba czasu. Mam go ostatnio jak na lekarstwo.

**Comment by Majkovsky** [comment]
Może wystarczy podać inną zmienną, kwestia paru minut, aby zaktualizować skrypt. Mogę podać kod źródłowy filmu prapremierowego, a w wolnej chwili możesz sprawdzić ten kod.

**Comment by zacny** [comment]
Ja się tego nie podejmę, ale możesz próbować na forum skryptu. Może tak uzyskasz pomoc.
