### ISSUE TITLE
Niestety natrafiono na problem, który uniemożliwił dalsze działanie

### ISSUE THREAD

**Issue by legendarek** [zacny/voddownloader#58]
Cześć,
nie mogę pobrać z vod.tvp.pl
Nie można znaleźć źródła

**Comment by zacny** [comment]
Może jakieś szczegóły?

**Comment by legendarek** [comment]
Koło fortuny, odc 739
Niestety natrafiono na problem, który uniemożliwił dalsze działanie
Nie udało się odnaleźć źródeł do materiału.
Materiał ze strony https://vod.tvp.pl/video/kolo-fortuny,odc-739,46980509 nie posiada zdefiniowanych źródeł, które mogłyby zostać wyświetlone.
Może to oznaczać, że nie jest on publicznie dostępny, dostępne źródła nie mogą zostać wyświetlone w przeglądarce bez dodatkowego oprogramowania lub jest umieszczony w płatnej strefie.
Informacje o systemie: Chrome 80.0.3987.149 on Windows 10 64-bit
Wersja pluginu: 4.9
Wersja skryptu: 6.11.2

**Comment by zacny** [comment]
Komunikat nie kłamie. Nie ma dostępnych źródeł do pobrania. Możesz spróbować ściągnąć sobie na podstawie tego:
https://r.dcs.redcdn.pl/hls/o2/TVP/embeddrm/out/kolo-fortuny-20200325_28a7cab5ed8783c0c8b67dda10b4a0ee.mp4/fairplay/playlist.smil/playlist.m3u8
