### ISSUE TITLE
player.pl / monit logowania

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#60]
wygląda na to ze na player.pl skrypt obecnie nie funkcjonuje z powodu:
https://player.pl/programy-online/ameryka-express-odcinki,13593/odcinek-9,S02E09,167937

![obraz](https://user-images.githubusercontent.com/50556762/81331775-644b9c80-90a2-11ea-8bc5-595bf7098274.png)

czyli na materiale jest informacja o tym aby sie zalogować, na paru losowych tez tak jest, dlatego skrypt sie nie uaktywnia i nie wysweitla guzika...

... ale recznie jsona pobrać mozna i nie jest on blokowany.

**Comment by zacny** [comment]
By to poprawić skrypt będzie się musiał zachowywać tutaj nieco inaczej niż na innych portalach. Przygotuję wersję próbną i zobaczymy czy tak zostanie.

**Comment by zacny** [comment]
Ostatnia aktualizacja powinna rozwiązać problem.

**Comment by funplayertv** [comment]
wygląda na to ze działa, ale przyznam się szczerze, ze nie spojrzałem na Twojego screena na początku i chwile mi zajeło znalezienie tej nowej ikony :D

**Comment by zacny** [comment]
No właśnie obawiam się teraz problemów z tego powodu. A innego dobrego pomysłu nie mam.
