### ISSUE TITLE
ninateka - znajduje tylko 360p (a i tak nie można pobrać)

### ISSUE THREAD

**Issue by miroszak** [zacny/voddownloader#61]
Na stronie ninateka.pl wtyczka znajduje tylko materiały w 360p (640x360). Zresztą, i tak nie można ich bezpośrednio pobrać (chociaż "kopiuj" i "otwórz" zwracają poprawne linki do video w 360p)...

**Comment by zacny** [comment]
Jedynie taka rozdzielczość jest możliwa do pobrania. Inne rozdzielczości są rozpowszechniane jako strumienie. Pobrać mogę bez problemu. Jakiś przykładowy link?

**Comment by miroszak** [comment]
Dziękuję za szybką odpowiedź i przepraszam, że nie wkleiłem przykładowego linku od razu. Np. tego https://ninateka.pl/film/ostatni-w-aleppo-feras-fayyad
Tu na pewno są wyższe rozdzielczości, chociaż w playerze pomyliła im się rozdziałka pionowa z poziomą (1920p to 1080p:), ale realnie na pewno jest co najmniej 720... Wydaje mi się, że 360p i tylko 360p znajduje i dla innych materiałów (np.koncerty) - nawet, jeśli powinno być więcej.

**Comment by zacny** [comment]
Tak jak pisałem wcześniej. Wyższa jakość jest przechowywana w częściach (strumieniach) i nie jest możliwa do ściągnięcia w formie jednego pliku. Trzeba użyć narzędzia, które potrafi ściągnąć poszczególne części, a potem jeszcze je połączy w jeden wynikowy plik. Nie wiem czy jest to do zrobienia jedynie za pomocą javascriptu (języka w którym zbudowany jest ten skrypt). 
Zwykle najniższa jakość jest przechowywana w postaci możliwej do pobrania. Do niej właśnie można się dostać z pomocą skryptu. W podanym linku jest chyba jakiś problem z opcją pobierania. Podejrzewam, że tytuł zawiera znaki "|" i to jest przyczyną. 
Materiał można otworzyć i potem pobrać.

**Comment by telemach1337** [comment]
jak wyżej, ten film można bez problemu pobrać takim narzędziem które skleja i muxuje

**Comment by funplayertv** [comment]
> 
> 
> jak wyżej, ten film można bez problemu pobrać takim narzędziem które skleja i muxuje

ale skrypt nie działa na tej zasadzie, mozesz samodzielnie uzyc narzedzia np. youtube-dl jedynie;

**Comment by miroszak** [comment]
Dziękuję wszystkim za poświęcony czas wyczerpujące odpowiedzi.
@zacny - Najwyższe uznanie za skrypt. Działa super!

Temat do zamknięcia, a nawet do kosza. Zgłoszony problem nie jest de facto błędem voddownloadera:)

**Comment by zacny** [comment]
Być może kiedyś uda mi się usprawnić nieco działanie skryptu dla ninateki. Mam pewne pomysły, niestety na wszystko potrzeba czasu.

**Comment by miroszak** [comment]
Spoko, dzięki społeczności doszedłem do działającej obecnie na ninatekę metody - wyszukanie pierwszego manifest.mpd podczas odtwarzania filmu i skopiowanie z niego adresu video, a resztę zrobi i w całości dociągnie youtube-dl (czy w moim przypadku dlg, bo jako stary Amigowiec bez GUI nie daję rady:) 
Mniejsza z niną, do vod.pl i vod.tvp.pl (gdzie indziej nie testowałem) skrypt jest bezkonkurencyjny i raz jeszcze za jego stworzenie dziękuję. Podobnie jak za zaangażowanie w wątek.
 
Pozdrawiam serdecznie.
 
 
W dniu 2020-05-10 20:53:46 użytkownik zacny <notifications@github.com> napisał:
 
Być może kiedyś uda mi się usprawnić nieco działanie skryptu dla ninateki. Mam pewne pomysły, niestety na wszystko potrzeba czasu.
