### ISSUE TITLE
Problem z VOD TVP

### ISSUE THREAD

**Issue by telemach1337** [zacny/voddownloader#62]
Ten materiał jest bezpłatny a jednak nie udaje się ściągnąć 

https://vod.tvp.pl/video/hakerzy-dla-wolnosci,hakerzy-dla-wolnosci,45611673

Nie udało się odnaleźć źródeł do materiału.
Materiał ze strony https://vod.tvp.pl/video/hakerzy-dla-wolnosci,hakerzy-dla-wolnosci,45611673 nie posiada zdefiniowanych źródeł, które mogłyby zostać wyświetlone.

Wersja pluginu: 4.10.6112
Wersja skryptu: 6.14.2

**Comment by zacny** [comment]
Materiał nie jest dostępny do ściągnięcia. Jest tylko w formie streama. Można wykorzystać np. youtube-dl:
https://r.dcs.redcdn.pl/dash/o2/TVP/embeddrm/out/hakerzy-dla-wolnosci-20191202_5426ee50dff5db67d99ab122f4426fde.mp4/Manifest.ism

**Comment by telemach1337** [comment]
czy na pewno Ci się ściąga czy tylko masz przypuszczenia że jest dostępny ?

**Comment by zacny** [comment]
Metadane pliku wskazują na to, że można sobie to w ten sposób pobrać. Czy tak jest w rzeczywistości nie sprawdzałem.

**Comment by telemach1337** [comment]
no i się wyjaśniło, przyczyną jest DRM

**Comment by telemach1337** [comment]
fajnie by było gdybyś przerobił skrypt tak aby wykrywał strumieniowe lub DRM i nie wyświetlał komunikatu 'POBIERZ' tylko 'TEGO FILMU NIE DA SIĘ POBRAĆ'
bo skoro jest POBIERZ a się nie pobiera to wniosek jest taki że coś nie działa i trzeba tu zgłosić a w praktyce to jest zawracanie głowy bo się nie pobiera gdyż się ma nie pobierać

**Comment by zacny** [comment]
Teraz jest taki komunikat:
`
Może to oznaczać, że nie jest on publicznie dostępny, dostępne źródła nie mogą zostać wyświetlone w przeglądarce bez dodatkowego oprogramowania lub jest umieszczony w płatnej strefie.
`
Przycisk się wyświetla, ale informacje o tym czy pobranie jest możliwe czy nie są dostępne dopiero po wykonaniu szeregu operacji. Musiałbym to wszystko wykonać zanim pokażę przycisk, a to by spowalniało działanie strony. Są przypadki gdzie tych sprawdzeń musiałbym wykonać kilkanaście, bo tyle jest wykrywanaych materiałów na stronie.

**Comment by telemach1337** [comment]
słowo może daje 50% więc chyba lepiej zamiast POBIERZ zrobić SPRAWDŹ MOŻLIWOŚĆ POBRANIA i wtedy jedzie od 0 do 100% jak wynik pozytywny to super a inaczej to już wiadomo co i jak; chyba dla ciebie lepiej żeby użytkownik poczekał te parenaście sekund niż żebyś ty potem tracił czas na zamykanie case'ów

**Comment by HerMajestyDrMona** [comment]
W 99% przypadków komunikat wyświetla prawidłowe informacje. Możliwym rozwiązaniem jest zmiana tekstu przycisku "Pobierz" na "Spróbuj Pobrać" lub "VOD Downloader". Być może pojawiłoby się wtedy mniej zgłoszeń tego typu. Z drugiej jednak strony czasami zdarzają się przypadki jakiejś zmiany w API wymagające poprawki, jednak takie weryfikacje można miesięcznie przeprowadzać na przykładowych materiałach.

**Comment by zacny** [comment]
Nie ma już przycisku pobierz :D
