### ISSUE TITLE
ipla.tv - ikona pobierania

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#64]
https://www.ipla.tv/wideo/serial/Pierwsza-milosc/828/Odcinki-2501-4000/5010718/Pierwsza-milosc-Odcinek-3057/b1b5de06c229e012138d47f2d9136568?seasonId=5010718

moze wartoby tutaj dac biały kolor ikony pobierania, bo teraz jest ona niewidoczna...

**Comment by zacny** [comment]
Błąd po zmianach styli.
