### ISSUE TITLE
Pobieranie z CDA.pl nie działa

### ISSUE THREAD

**Issue by sevospl** [zacny/voddownloader#65]
Hi.

Tampermonkey BETA, włączone API przeglądarki, próbowałem z Brave i Firefox.

Niezależnie od rodzaju materiału i jego jakości, nie wyświetla się przycisk pobierania - jakiś czas temu był, ale linki do pobierania w ogóle nie działały. Wydaje mi się, że coś się zmieniło.

**Comment by zacny** [comment]
![cda](https://user-images.githubusercontent.com/20001050/81751703-4326e980-94b0-11ea-9308-e4eb41787263.png)

**Comment by sevospl** [comment]
Ok, dopiero teraz zauważyłem tę ikonę "kamery" - myślałem, że to część playera cda.

W każdym razie, po naciśnięciu pojawiło się źródło do pobrania, ale nie działa - kliknięcie nic nie robi. Klikam "otwórz" i wywala błąd, że plik nie został znaleziony.

**Comment by zacny** [comment]
Podaj link.

**Comment by sevospl** [comment]
> Podaj link.

https://github.com/zacny/voddownloader/issues/65#issuecomment-627636649

**Comment by sevospl** [comment]
> Podaj link.

https://www.cda.pl/video/327021181/vfilm?wersja=1080p

**Comment by HerMajestyDrMona** [comment]
"Ten film jest dostępny dla użytkowników premium", lol.

**Comment by zacny** [comment]
Ten skrypt materiałów premium nie wspiera.

**Comment by sevospl** [comment]
Ok, sorry. :)
