### ISSUE TITLE
Dodatkowe informacje w opisie skryptu

### ISSUE THREAD

**Issue by zacny** [zacny/voddownloader#66]
Czy mógłbyś dodać w opisie skryptu jakieś screeny z użycia. Widzę, że po zmianach jest sporo nieporozumień i takie podejście mogłby wyeliminować część niepotrzebnych wątków.

**Comment by HerMajestyDrMona** [comment]
Gotowe, kiedyś jeszcze nad tym popracuję.

**Comment by zacny** [comment]
Chodziło mi bardziej o obrazki z 2-3 serwisów. W tym player.pl, żeby było widać, że tam jest inaczej. Screeny przygotuję Ci na githubie.
