### ISSUE TITLE
powiadomienie o zmianach jako popup

### ISSUE THREAD

**Issue by funplayertv** [zacny/voddownloader#67]
ostania zmiana ikony na player pokazuje ze ludzie nie ogarniają, czy można *technicznie* zrobić jakieś powiadomienie z lista zmian ktore by wyskakiwało po aktualizacji skryptu albo przy aktywaccji i użytkownik musial by to zobaczyć i tam naspiac np. o zmianie lokalizacji ikony itd ? @zacny

**Comment by zacny** [comment]
Zmodyfikujemy opis skryptu i dodamy zrzuty ekranu.

**Comment by xxcriticxx** [comment]
czemu w ogole guzik zostal zmieniony na ikone bialej kamery?

**Comment by HerMajestyDrMona** [comment]
Ikonka została zmieniona, ponieważ ludzie uważali że jak jest napisane "Pobierz" to skrypt ma w 100% działać i wyciągać linki do materiałów. Wyjaśniające komunikaty o możliwym DRM lub braku źródła były w niektórych przypadkach ignorowane, a problemy tego typu nagminnie zgłaszane.

Po jakimś czasie starsi użytkownicy ogarną zmianę, a nowi nie powinni mieć z tym problemu, chociażby po przeczytaniu opisu.

Ikonka kamery to alternatywa dla proponowanych dłuższych napisów "Spróbuj pobrać", "VOD Downloader", itd. Dodatkowo, ikona znika teraz gdy materiał jest odtwarzany (nie trzeba wyłączać rozszerzenia w razie chęci obejrzenia bezpośrednio na VOD).

**Comment by xxcriticxx** [comment]
@HerMajestyDrMona dzieki za wytlumaczenie sytuacji

**Comment by zacny** [comment]
@HerMajestyDrMona Dodałem screeny w opisie na githubie. Przenieś to proszę w miarę możliwości na greasyfork.
