### ISSUE TITLE
Brak okienka w gornym lewym rogu do pobrania

### ISSUE THREAD

**Issue by Rafu7s** [zacny/voddownloader#68]
1. Otworz program TV na TVN player https://player.pl/programy-online/ameryka-express-odcinki,13593/odcinek-12,S02E12,167940
2. Zaloguj sie na konto
3. Nacisnij w lewym gornym rogu button pobierz

-przycisk do pobrania materialu przestal sie wyswietlac, nie idzie pobrać.

![Adnotacja 2020-05](https://user-images.githubusercontent.com/37976003/82589374-587cd180-9b9c-11ea-93c0-9d093405294d.jpg)

**Comment by HerMajestyDrMona** [comment]
U mnie jest:
![Annotation 2020-05-21 202344](https://user-images.githubusercontent.com/24290461/82592426-2fab0b00-9ba1-11ea-9700-94f355e83e79.png)

**Comment by zacny** [comment]
Przeczytać o zmianach:
https://github.com/zacny/voddownloader
potem zgłaszać ewentualne błędy.

**Comment by Rafu7s** [comment]
Dobra, działa :) Ale musiałem odinstalować skrypt i od nowa zainstalować, bo inaczej nie było tej ikonki. Dzięki, następnym razem zorientuje się lepiej w temacie zanim napisze.
