### ISSUE TITLE
Skrypt linkuje do vod.pl zamiast do player.pl

### ISSUE THREAD

**Issue by alvinek** [zacny/voddownloader#70]
Kiedy wejdziemy w player.pl i zamkniemy zakładkę ze stroną główną, pokazuje nam się błąd, w którym link zamiast do player.pl prowadzi do vod.pl: 
![obraz](https://user-images.githubusercontent.com/14000976/84807611-caafcd00-b007-11ea-81b4-0a994fad3423.png)

Ten sam bug pojawia się, gdy nie załadował się jeszcze player:
![obraz](https://user-images.githubusercontent.com/14000976/84807834-1f534800-b008-11ea-89b8-11e0e300e0fc.png)

Ścieżka jest dobra, domena jest zła.

Jedno i drugie (vod i player) wygląda na podobne, ale trochę mnie zmyliło, myślałem że skrypt się zepsuł :D

**Comment by zacny** [comment]
To było spowodowane zmianami na stronie. Nowa wersja zachowuje się poprawnie.
