### ISSUE TITLE
Ipla.tv - vod:not_accessible

### ISSUE THREAD

**Issue by LiquidLemon** [zacny/voddownloader#71]
Hej, przepraszam, że męczę tematem, który jest niezwiązany z samym rozszerzeniem, ale próbowałem pobrać właśnie materiał, który jeśli dobrze rozumiem jest zwyczajnie niedostępny w formie pojedynczego pliku MP4. Zakładam, że jest to po prostu ograniczenie API, z którego korzystacie i nie jest to coś co można jakkolwiek obejść. Czy jest może jakiś inny sposób pobrania tego materiału? W monitoringu sieci widzę dwa pobierane częściami strumienie audio i wideo, czy jest znany jakiś sposób na ich połączenie?

Link do odcinka: https://www.ipla.tv/wideo/rozrywka/Ninja-Warrior-Polska/5016778/Sezon-2/5022391/Ninja-Warrior-Polska-2-Odcinek-3/9c4bdd7bb38ae9e8e32fef8428691795?seasonId=5022391

Testowane lokalizacje (z logów rozszerzenia): 
https://getmedia.redefine.pl/vods/get_vod/?cpid=1&ua=www_iplatv_html5/12345&media_id=9c4bdd7bb38ae9e8e32fef8428691795

https://getmedia.redefine.pl/vods/get_vod/?cpid=1&ua=mipla_ios/122&media_id=9c4bdd7bb38ae9e8e32fef8428691795

**Comment by zacny** [comment]
Ten materiał jest zabezpieczony. Są odrębne strumienie audio i video. Video jest dodatkowo zaszyfrowany. Nie znam sposobu ani narzędzie do połączenie tego w jeden odszyfrowany plik.

**Comment by LiquidLemon** [comment]
Dzięki, poczytałem więcej i wychodzi, że całość jest za DRM, będę to musiał nagrać z ekranu.
