### ISSUE TITLE
player.pl nie działa

### ISSUE THREAD

**Issue by martiinezz** [zacny/voddownloader#72]
Coś chyba TVN nazmieniał i nie mogę pobrać pliku np dla tego:
https://player.pl/programy-online/101-napraw-odcinki,3804
To na FF.
Zalogowany czy nie widzę nigdzie kamerki do kliknięcia:

![image](https://user-images.githubusercontent.com/19732099/94370547-02431080-00f1-11eb-8208-e3ea15312edf.png)

Na chrome zaś mam kamerkę do kliknięcia, ale kończy się:

![image](https://user-images.githubusercontent.com/19732099/94370701-bc3a7c80-00f1-11eb-9a29-6a39ace0763e.png)

**Comment by zacny** [comment]
Temat wałkowany wielokrotnie. Zasilacz z czarnej listy. Zamykam.
A tak na poważnie to wybierz sobie konkretny odcinek, albo przesuń stronę suwakiem trochę w dół, by pojawiła się ektykieta "właśnie oglądasz" i będzie działać. Temat rzeczywiście był już wałkowany na forum.

**Comment by martiinezz** [comment]
Faktycznie działa na konkretnym odcinaku, ale tylko w chrome :( - ale lepsze to niż nic :) dzięki !!!

**Comment by zacny** [comment]
Ja sprawdzałem na firefoxie 80.0.1
