### ISSUE TITLE
CDA

### ISSUE THREAD

**Issue by minaa13** [zacny/voddownloader#74]
Problem z CDA - teoretycznie rozpoczyna pobieranie pliku, jednak nic nie pobiera...

**Comment by zacny** [comment]
Pomyśl proszę, co ja mam z tym Twoim zgłoszeniem zrobić? Jak niby ustawlić przyczynę problemu? Proszę poprawić zgłoszenie tak by można było zobaczyć co się dzieje i w jakiej sytuacji. Podać przykład.

**Comment by minaa13** [comment]
Sytuacja jest taka: mam wykupione CDA premium. Część filmów (np. Książę i ja), które są tam dostępne można bez problemów ściągnąć. Zapisują się i działają. Problem jest natomiast np. z tym http://prntscr.com/v73o13 Dokładnie tak to wygląda. Jest komunikat o rozpoczęciu pobierania, ale nie pobiera. 
Jest też inna sytuacja. kilka filmów ma ustawioną opcję "niedostępny w Twoim kraju". Po ustawieniu przez VPN innego kraju film się wyświetla, ale w tampermonkey jest brak skryptu. Wraca do normy po zapauzowaniu filmu i powrocie do polskiego IP, ale znowu sytuacja jak wyżej - komunikat o rozpoczęciu pobierania i brak takowego.

**Comment by zacny** [comment]
Jeżeli nie trafiłeś tutaj przez forum greasyfork to pewnie nie widziałeś opisu skryptu tam zamieszczonego:
https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod
Przeczytaj uważnie taką uwagę na dole odnośnie płatnych materiałów.
