### ISSUE TITLE
Nie działa player.pl

### ISSUE THREAD

**Issue by tomek3001** [zacny/voddownloader#75]
Siema, jest w ogóle możliwość zrobienia żeby skrypt działał dla materiałów wymagających logowania się?

**Comment by zacny** [comment]
Jeżeli chodzi o płatne materiały, to nie ma takiej możliwości. Inne powinny działać chyba tak samo zarówno bez logowania jak i po zalogowaniu. Czy tak jest na pewno, to w zasadzie nie pamiętam, bo zwyczajowo testy po zmianach robię bez logowania.

**Comment by tomek3001** [comment]
Nie no, darmowe jak dotąd działały bez problemu, jednak teraz chciałem pobrać materiały dostępne dopiero po wykupieniu pakietu i znalazłem informację o braku takiej opcji i chciałem się dowiedzieć czy powodem są ograniczenia techniczne, czy po prostu nikt się za to nie zabrał. Tak czy siak dobra robota.

**Comment by tomek3001** [comment]
Ok, czyli tak jak myślałem, dzięki.
