### ISSUE TITLE
cda...

### ISSUE THREAD

**Issue by fcln1979** [zacny/voddownloader#76]
Niestety cda nie jest wspierane...
Próbowałem na ff i na chromie.
Proszę o pomoc.

**Comment by zacny** [comment]
Prosisz o pomoc samemu nie udzielając żadnych informacji. Szczegóły proszę.

**Comment by zacny** [comment]
Nie zauważyłem, żadnych niedogodności w działaniu skryptu. Nie dostarczyłeś również żadnych szczegółowych informacji o problemie, tak jak prosiłem. Temat uważam zatem za zamknięty.
