### ISSUE TITLE
Niejasne zachowanie na CDA

### ISSUE THREAD

**Issue by Silver-Ankh** [zacny/voddownloader#77]
Mam wykupione Premium, mogę oglądać wszystkie filmy w przeglądarce. Ale nie wszystkie mogę ściągnąć. Na niektórych filmach po naciśnięciu Pobierz pokazuje się komunikat "Rozpoczęto pobieranie" ale nic więcej się nie dzieje. Nie wiem czy chodzi o filmy Premium, ale jeżeli nie da się ściągnąć takich filmów, to może przydałby się jakiś komunikat, bo teraz to nie wiadomo dlaczego dany film nie działa, a komunikat "Rozpoczęto pobieranie" wskazuje, że powinno być OK a nie jest.

**Comment by HerMajestyDrMona** [comment]
https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod

"Skrypt nie działa z płatnymi materiałami, bądź materiałami zabezpieczonymi DRM / autoryzacją wymagającą zalogowania się. Głównym celem jest możliwość obejrzenia darmowych programów/seriali na starszych telewizorach, bez dedykowanych polskich aplikacji VOD. Nawet gdyby możliwość wyciągania płatnych materiałów istniała - nie zostanie ona dodana do tego skryptu. "

**Comment by zacny** [comment]
@Silver-Ankh 
Tak jak kolega napisał. Dla materiałów premium nie działa i działać nie będzie, bo tam są dodatkowe zabezpieczenia. Nie bardzo też jest możliwość dorobienia jakiegoś komunikatu tam, bo osobiście konta premium nie posiadam. Nawet nie wiem czy byłaby taka możliwość, to trzeba by jakoś rozróżniać jaki to materiał. Teraz skrypt zawsze ma takie samo działanie, niezależnie od tego co próbujemy pobrać.
