### ISSUE TITLE
ipla

### ISSUE THREAD

**Issue by martiinezz** [zacny/voddownloader#79]
Publicznie dostępny materiał:

https://www.ipla.tv/wideo/rozrywka/Love-Island-Wyspa-milosci/5016776?seasonId=5022387

A jednak zwraca błąd :( - strumień leci jako blob?

**Comment by zacny** [comment]
Skrypt zadziała dla każdego materiału, który jest opatrzony międzyinnymi taką ikoną. Podany przykład jej nie ma, dlatego nie działa.
![obraz](https://user-images.githubusercontent.com/20001050/99197585-b8db7d00-2793-11eb-8032-add894320de0.png)
