### ISSUE TITLE
Player TVN automaniak

### ISSUE THREAD

**Issue by AlfredArtemis** [zacny/voddownloader#80]
![Przechwytywanie](https://user-images.githubusercontent.com/74860993/99903369-350a1f00-2cc4-11eb-88d1-eda93958aac4.JPG)

**Comment by xxcriticxx** [comment]
@AlfredArtemis trzeba wykupic dostep do odcinka nie będzie dzialal ze skryptem

**Comment by zacny** [comment]
Wygląda na jakiś odcinek przedpremierowy dostępny po wykupieniu dostępu. Poczekaj pewnie za jakiś czas odblokują.
