### ISSUE TITLE
Podczas błędu pobierania, skrypt poprawnie ponawia pobieranie lecz nazwa pliku to 'video-4' co powoduje problem.

### ISSUE THREAD

**Issue by RafiXWPT** [zacny/voddownloader#82]
Jak w tytule. Gdy wystąpi błąd pobierania, następuje ponowna próba lecz wynikowy plik ma nazwę 'video-4'. Gdy takich plików jest 10, kompletnie nie wiadomo co to za odcinek, trzeba skasować i tak na prawdę pobierać od początku

**Comment by zacny** [comment]
Nigdy mi się chyba tak nie przydarzyło. Możesz podać ścieżkę jak zreplikować taki błąd? Może jakiś sposób jak to zasymulować?

**Comment by RafiXWPT** [comment]
Udało mi się ograniczyć pole gdzie taki błąd występuje. Dzieje się to gdy pobieramy treści z tvpvod - przeglądarka Chrome. Jak otwieram ponad 10 zakładek naraz z odcinkami i uruchamiam pobieranie jednocześnie, prawie zawsze się zdarzy, że zerwie w którymś momencie i będzie ten błąd. W przypadku CDA nie uzyskałem takiego błędu

**Comment by zacny** [comment]
To chyba nic dziwnego, że przy takiej ilości pobrać z serwera jednocześnie zrywa się połączenie. Ewidentnie mogą w takim wypadku występować problemy sieciowe. Ja mam tak nawet przy 3+ pobieraniach (pewnie dużo zależeć tu będzie od jakości łącza). Używam jednak firefoxa, on radzi sobie zwykle z ponowieniem/kontynuowaniem pobierania w takiej sytuacji. Jeżeli dobrze zrozumiałem i używana przez Ciebie przeglądarka tego nie potrafi, to nie jest to winą skryptu.
Jeżeli problem jest zgoła inny, wyprowadź mnie proszę z błędu.

**Comment by HerMajestyDrMona** [comment]
Zakładam, że przy wystąpieniu błędu pobierania, @RafiXWPT w CTRL+J, klika w link pod nazwą (lub przycisk ponowienia) i pobieranie rozpoczyna się od początku, z domyślną nazwą z serwera. Tylko jaki to ma związek z działaniem skryptu, którego karta już pewnie dawno została zamknięta to ja nie wiem. Prawdopodobnie to udogodnienie, które umożliwia zapisanie z poprawną nazwą (z poziomu z karty z linkami, pod przyciskiem "Pobierz") sprawia wrażenie jakoby nazwa plików pochodziła z serwerów, a w praktyce jest to trick / udogodnienie wykonywane przez aktywny skrypt.

**Comment by RafiXWPT** [comment]
@zacny @HerMajestyDrMona, w przypadku Chrome ponowne pobieranie samo sie triggeruje (zakladki ze skryptem mam dalej otwarte i nie klikam ręcznie ponowienia), zmienia się jednak automatycznie nazwa pliku na 'video-4'. Samo zrywanie połączenia nie jest tu problemem, lecz to, że gdy to sie stanie zmienia się nazwa pliku. Sprawdzę to następnym razem w firefoxie, byćmoże rzeczywiście to kwestia samej przeglądarki i tam nie będzie tego problemu.

**Comment by zacny** [comment]
I jak sprawdziłeś?

**Comment by zacny** [comment]
Sprawdziłem to ponownie i nie widzę takich problemów na firefoxie, którego zwyczajowo używam. Zakładam zatem, że to jakiś problem z przeglądarką, bądź implementacją wtyczki tampermonkey na tę przeglądarkę. Skrypt w takie rzeczy nie interweniuje, bo to niemożliwe.
