### ISSUE TITLE
nie moge pobrać filmu!!

### ISSUE THREAD

**Issue by silverq1233** [zacny/voddownloader#83]
Niestety natrafiono na problem, który uniemożliwił dalsze działanie
Nie udało się odnaleźć metadanych tego materiału.
Materiał ze strony https://vod.pl/filmy/piraci-z-karaibow-skrzynia-umarlaka-caly-film-online/hpevwk8 nie posiada zdefiniowanych metadanych potrzebnych do działania skryptu lub są one nieprawidłowe.

Może to oznaczać, że nie jest to materiał publicznie dostępny, nie posiada zdefiniowanych źródeł lub nie mogą one zostać wyświetlone w przeglądarce bez dodatkowego oprogramowania albo jest to materiał umieszczony w płatnej strefie.
Informacje o systemie: Chrome 87.0.4280.88 on Windows 10 64-bit
Wersja pluginu: 4.11
Wersja skryptu: 7.2.4

oto błąd który mi wyskakuje

**Comment by HerMajestyDrMona** [comment]
Przecież "błąd" wyjaśnia w czym jest problem.

**Comment by zacny** [comment]
Materiał jest płatny, co nie jest oczywiste do stwierdzenia akurat na tej stronie, ale np tutaj już widać to wyraźnie:
https://vod.pl/filmy/piraci-z-karaibow-skrzynia-umarlaka-caly-film-online/hpevwk8#search/0/0/0/0/0/skrzynia%20umarlaka
Skrypt płatnych materiałów nie wspiera.
