### ISSUE TITLE
nie pobiera filmu 

### ISSUE THREAD

**Issue by careaaaaaaaa** [zacny/voddownloader#84]
Niestety natrafiono na problem, który uniemożliwił dalsze działanie
Nie udało się odnaleźć metadanych tego materiału.
Materiał ze strony https://player.pl/playerplus/seriale-online/nieobecni-odcinki,27443/odcinek-2,S01E02,185196 nie posiada zdefiniowanych metadanych potrzebnych do działania skryptu lub są one nieprawidłowe.

Może to oznaczać, że nie jest to materiał publicznie dostępny, nie posiada zdefiniowanych źródeł lub nie mogą one zostać wyświetlone w przeglądarce bez dodatkowego oprogramowania albo jest to materiał umieszczony w płatnej strefie.
Informacje o systemie: Chrome 87.0.4280.88 on Windows 10 64-bit
Wersja pluginu: 4.11
Wersja skryptu: 7.2.4

**Comment by zacny** [comment]
https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod
A teraz pytanie retoryczne. Czy to nie jest czasami płatny materiał?
