### ISSUE TITLE
Player nie działa

### ISSUE THREAD

**Issue by KarwaszTwarz** [zacny/voddownloader#90]
Pomimo posiadania konta z wykupionym abonamentem nie mogę pobrać filmów z Player.
Komunikat:
`Nie udało się odnaleźć metadanych tego materiału.`

**Comment by zacny** [comment]
Znam problem. Rozwiązanie niestety nie jest proste o ile w ogóle możliwe. Player jest już tylko płatny więc rozważam usunięcie go ze wspracia skryptu jeżeli wszystko inne zwiedzie.

**Comment by zacny** [comment]
Tutaj jest już opisane o co chodzi.
https://github.com/zacny/voddownloader/issues/86
