### ISSUE TITLE
Po instalacji na nowej przeglądarce nie działa

### ISSUE THREAD

**Issue by XantorXD** [zacny/voddownloader#93]
Instalacja skryptu która do tej pory była zainstalowana działa bez problemu, ale po zainstalowaniu skryptu od nowa na innym koncie przeglądarki skutkuje tym że skrypt w ogóle się nie uruchamia. Nie pojawia się ikona kamerki.

**Comment by HerMajestyDrMona** [comment]
Proszę spróbować (testowo) wersji z: https://github.com/zacny/voddownloader/issues/94#issuecomment-910877015
Z jakichś powodów domena gitcdn.xyz na której znajdowały się niektóre zewnętrzne skrypty nie ładuje się i przez to voddownloader nie działa u wszystkich.

**Comment by XantorXD** [comment]
Dzięki wielkie! Działa :)

**Comment by robson1410** [comment]
na polsatgo już nie działa, można to jakoś naprawić.

**Comment by X3nuPL** [comment]
nie dziala na TVP VOD.
