### ISSUE TITLE
Ipla nie działa na chrome i firefox

### ISSUE THREAD

**Issue by olek52** [zacny/voddownloader#94]
Ipla nie działa na chrome i firefox   brak  ikony

**Comment by HerMajestyDrMona** [comment]
Przykładowy materiał? U mnie wyświetla się prawidłowo.

**Comment by olek52** [comment]
Wchodze na stronę IPLA   i  brak ikony  który  się ukazywała   aby można było przejść    pobierania    serial Górale  to serial który  pobierałem od  początku powstania  a  teraz  nawet na tym  brak mi ikony  przeglądarka  Chrome jak i   Firefox   i sam  nie wiem jaka przyczyna   ,  już poszedłem na inny komputer   bo myślałem  że coś  przyłapałem  alei tam   .. Windows  10  64  bit Chrome  wersja 92.0.4515.159    proszę  o pomoc   https://www.ipla.tv/wideo/rozrywka/Gorale/5013578

**Comment by HerMajestyDrMona** [comment]
U mnie przycisk pobierania wyświetla się bez problemu: https://i.imgur.com/OBaXgOE.png

Być może dostałeś adres IP od dostawcy, który ma niepoprawnie przypisany kraj w ich bazie geoIP? Ciężko powiedzieć bez możliwości reprodukcji problemu :(

**Comment by olek52** [comment]
" geoIP?"  i  tu  raczej  nie ten  problem   bo mam stałe IP  od  6  lat   gdzie przedtem  nie było problemu

**Comment by HerMajestyDrMona** [comment]
Na pewno masz włączony skrypt w ustawieniach Tamper Monkey na danej stornie VOD? https://i.imgur.com/GsLb72Y.png

**Comment by olek52** [comment]
tak  mam   ma tak   https://zapodaj.net/885872527ab78.png.html

**Comment by olek52** [comment]
I problem sam się rozwiązał  IPLA  znikła  teraz  już tylko   https://polsatboxgo.pl  oraz   https://polsatgo.pl  ...  Teraz  czekamy na wasze złote  rączki  :)

**Comment by HerMajestyDrMona** [comment]
Zainstaluj proszę moją starą wersję (4.9) z dodatkiem polsatbox: https://pastebin.com/raw/tpsUE088
I zobacz jak działa.

Przy nowszych wersjach (stworzonych przez @zacny) ciężko mi się połapać i cokolwiek zmienić. Pierwsze próby (kilka dni temu) zakończyły się niepowodzeniem, ale może jeszcze się uda jakoś, z tym że nie mam czasu za dużo na zabawę z tym.

**Comment by SebaK666** [comment]
> 
> 
> Zainstaluj proszę moją starą wersję (4.9) z dodatkiem polsatbox: https://pastebin.com/raw/tpsUE088
> I zobacz jak działa.
> 
> Przy nowszych wersjach (stworzonych przez @zacny) ciężko mi się połapać i cokolwiek zmienić. Pierwsze próby (kilka dni temu) zakończyły się niepowodzeniem, ale może jeszcze się uda jakoś, z tym że nie mam za dużo czasu na zabawę z tym.
> 
> EDIT: O dziwo stara wersja działa też na VOD TVP.
> 
> Problem w tym, że nowe wersje zależą w dużej mierze od układu strony (detekcja czy przycisk pobierania powinien się pojawić czy nie). Jeśli dostawca zmieni coś w kodzie HTML, to wykrywanie przestaje działać. Stara wersja po prostu wyświetlała przycisk na każdej stronie spełniającej kryteria. Czasami ten przycisk działał, czasami nie, ale zawsze była próba wyciągnięcia materiałów.
> 
> EDIT2: Już mniej-więcej wiem o co chodzi.
> Domena gitcdn.xyz do której linkują nowe wersje skryptu nie działa i nie ładuje kilku funkcji z których korzysta skrypt.

Zrobiłeś na polsatgo.pl błąd, bo jest *polsatgo.pl*/ zamiast *polsatgo.pl/* dlatego nie wykrywa na tej stronie. Natomiast na vod.tvp.pl żaden niebieski przycisk u mnie się nie pojawia.

**Comment by HerMajestyDrMona** [comment]
To sprawdźcie jeszcze tą (nową) wersję z polsatgo: https://pastebin.com/raw/bAvHiNfi

Na VOD TVP powinna wyświetlać się kamerka ikonki. Tymczasowo zmienione gitcdn.xyz na bezpośredni link do githuba.

Polsatgo zabugowane. Będzie się wyświetlać ikonka kamerki ale tylko po CTRL+R (odświeżeniu strony), w lewym górnym rogu.

Jest to kwestia tej linii:

```
observer: {
	            anchor: 'body',
                mode : 'added',
	            selector: 'body'
	        },
```

Nie wiem na razie czym to można zastąpić, bo z innymi divami nie chciało działać, więc zostało na "body".

Może zacny wróci po wakacjach to poprawi :)

**Comment by SebaK666** [comment]
> 
> 
> To sprawdźcie jeszcze tą (nową) wersję z polsatgo: https://pastebin.com/raw/bAvHiNfi
> 
> Na VOD TVP powinna wyświetlać się ikonka kamerki. Tymczasowo zmienione gitcdn.xyz na bezpośredni link do githuba.
> 
> Polsatgo zabugowane. Będzie się wyświetlać ikonka kamerki ale tylko po CTRL+R (odświeżeniu strony), w lewym górnym rogu.
> 
> Jest to kwestia tej linii:
> 
> ```
> observer: {
> 	            anchor: 'body',
>                 mode : 'added',
> 	            selector: 'body'
> 	        },
> ```
> 
> Nie wiem na razie czym to można zastąpić, bo z innymi divami nie chciało działać, więc zostało na "body".
> 
> Może zacny wróci po wakacjach to poprawi :)

Tak, na nowej wersji na vod.tvp.pl jest teraz ikonka kamery. Ta ikona kamery też chyba wszędzie pokazuje się, ale pod warunkiem, że kursor ustawimy w polu wideo, co nie każdy może wiedzieć. Ale dobrze że cokolwiek poprawiłeś i z polsatgo można już wyciągać jakieś linki. Bo przykładowo DownloadHelper też wciąga linki - ale z DRM.

**Comment by olek52** [comment]
@HerMajestyDrMona    Dziękuję   pięknie świetna  robota   ....

**Comment by HerMajestyDrMona** [comment]
> @HerMajestyDrMona Dziękuję pięknie świetna robota ....
> 
> https://polsatgo.pl jeszcze jakby tak mozna te reklamy się pozbyć

uBlock Origin nie działa?

**Comment by olek52** [comment]
> > @HerMajestyDrMona Dziękuję pięknie robota ....
> > [https://pl.pl](https://polsatgo.pl) jeszcze tak mozna te reklamy się
> 
> uBlock Origin nie działa?


przy użyciu uBlock Origin  pojawia się komunikat  aby wyłaczyc  oprogramowanie do blokowania reklam  ale to tylko na   polsatgo.pl  patrz foto  https://zapodaj.net/56b06b4442cf2.png.html

**Comment by xxcriticxx** [comment]
@olek52 takie zgloszenia to tutaj sie podaje https://github.com/MajkiIT/polish-ads-filter

**Comment by olek52** [comment]
@xxcriticxx    dzięki z a info  ,   ale  widzę  że  cos  chyba  juz  jest   ale  co i jak  to jestem  zielony  ..możesz  jakoś  pomóc   .pomoc dla zielonego  .Dzięki

**Comment by maza506** [comment]
może mi ktoś podpowiedzieć jak zainstalować skrypt na polsat go

**Comment by olek52** [comment]
przejźd do Tampermonkey

punkt 1
1 - https://zapodaj.net/a0ea4c6e0aadd.png.html

punkt 2 skopiuj zawartośc tego https://pastebin.com/raw/bAvHiNfi

i wklej to tu https://zapodaj.net/84799211bad9a.png.html

3 - zakładka PLIK i zapisz https://zapodaj.net/1add1f35ddd1b.png.html

**Comment by HerMajestyDrMona** [comment]
Ma ktoś z Was pomysł czym zastąpić to "selector: 'body'" na polsatgo / boxgo aby wyświetlać ikonkę kamerki zawsze kiedy to potrzebne? Jakby udało się to polepszyć to spróbuję zaktualizować główny skrypt.

**Comment by elelek** [comment]
Czy komuś z tego skryptu działa ninateka?
U mnie nie wyświetla się ikonka do pobierania. Po odświeżeniu strony również nic się nie wyświetla.
Może się ktoś wypowiedzieć?

**Comment by 24Anja06** [comment]
Niestety, chyba znów nie jest możliwe pobieranie z polsatgo. 
Po kliknięciu w ikonkę kamerki wyskakuje taki komunikat:
https://zapodaj.net/bc7e995ba5d51.jpg.html
Da się jakoś temu zaradzić?

**Comment by SebaK666** [comment]
> 
> 
> Niestety, chyba znów nie jest możliwe pobieranie z polsatgo. Po kliknięciu w ikonkę kamerki wyskakuje taki komunikat: https://zapodaj.net/bc7e995ba5d51.jpg.html Da się jakoś temu zaradzić?

Prawdopodobnie weszłaś na program z DRM typu Twoja twarz czy Przyjaciółki. A nie każdy materiał można tak ściągnąć i to jest od dawna wiadome. Te programy na licencji zagranicznej, lub popularniejsze seriale mają DRM, a te bardziej "zwykłe" można tylko ściągać.

**Comment by username6669l** [comment]
nie mam pojecia o skryptach ale jakos uruchomilem na polsatboxgo. jesyneczka przy malpce tamper sie zaswiecila i kamerka do pobierania jest, moge sciagac 'chlopaki do wziecia'. dziekuje serdecznie :)

**Comment by username6669l** [comment]
> > To sprawdźcie jeszcze tą (nową) wersję z polsatgo: https://pastebin.com/raw/bAvHiNfi
> > Na VOD TVP powinna wyświetlać się ikonka kamerki. Tymczasowo zmienione gitcdn.xyz na bezpośredni link do githuba.
> > Polsatgo zabugowane. Będzie się wyświetlać ikonka kamerki ale tylko po CTRL+R (odświeżeniu strony), w lewym górnym rogu.
> > Jest to kwestia tej linii:
> > ```
> > observer: {
> > 	            anchor: 'body',
> >                 mode : 'added',
> > 	            selector: 'body'
> > 	        },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Nie wiem na razie czym to można zastąpić, bo z innymi divami nie chciało działać, więc zostało na "body".
> > Może zacny wróci po wakacjach to poprawi :)
> 
> Tak, na nowej wersji na vod.tvp.pl jest teraz ikonka kamery. Ta ikona kamery też chyba wszędzie pokazuje się, ale pod warunkiem, że kursor ustawimy w polu wideo, co nie każdy może wiedzieć. Ale dobrze że cokolwiek poprawiłeś i z polsatgo można już wyciągać jakieś linki. Bo przykładowo DownloadHelper też wciąga linki - ale z DRM.

dzieki 👍

**Comment by zacny** [comment]
W najnowszej wersji przycisk na polsatgo powinien się pojawić. Niestety wygląda na to, że został zmieniony algorytm pobierania informacji o video, zatem niewielki z tego będzie pożytek.

**Comment by HerMajestyDrMona** [comment]
Na Grasy Fork nie da się zaktualizować :(

"Script sync failed - Code uses an unapproved external script: @require https://raw.githubusercontent.com/zacny/voddownloader/4b17a120f521eaddf476d6e8fe3be152d506f244/lib/js/mdb-with-waves-patch.js."

**Comment by zacny** [comment]
Zgodnie z przewidywaniami.

**Comment by HerMajestyDrMona** [comment]
Była już kiedyś podoba sytuacja, bo nie pamiętam? Trzeba to ręcznie zaktualizować?

**Comment by olek52** [comment]
polsatbox.go  jeśli  się  nie  ukaże  ikona   pomaga   najechać  myszką  na  swój  film   i  myszka prawy  - Otwórz link w nowej  karcie   ....   u  mnie  na  chrome zawsze  pomogło

**Comment by HerMajestyDrMona** [comment]
Zabrakło jeszcze dodania polsatboxgo, jak w tej wersji testowej: https://pastebin.com/raw/bAvHiNfi

**Comment by zacny** [comment]
Nowa wersja to naprawiła. Zmodyfikowałem też algorytm wyszukiwania id dla tego serwisu.

**Comment by SebaK666** [comment]
Ten skrypt: https://pastebin.com/raw/bAvHiNfi w wersji 7.2.4 jest lepszy od tego 7.2.7 na polsatgo.pl, ponieważ ikona kamery pojawia nie dopiero na materiale wideo, a już o jeden stopień wcześniej, na stronie przed kliknięciem ">Oglądaj" Zróbcie więc mix obu skryptów, żeby pojawił się jeden, najlepszy możliwie skrypt.

**Comment by zacny** [comment]
A zauważyłeś, że pojawia się też tam gdzie nie powinien?

**Comment by SebaK666** [comment]
Nie. No oba pojawiają się np. na Fen 38, gdzie to jest w DRM, ale to nie wina skryptu. A masz coś na myśli, pytasz, czy coś wiesz więcej, widzisz błąd w skrypcie kolegi?

**Comment by HerMajestyDrMona** [comment]
Ten testowy skrypt miał niespójność z innymi serwisami, bo nie udało mi się tej ikonki kamery w inny sposób wyświetlić.

Pozostaje kwestia tego co zrobić ze skryptem na greasyfork. Może dodać aktualizację wyświetlającą powiadomienie o potrzebie instalacji z nowego źródła i pozbędziemy się tamtej stronki kompletnie?

**Comment by zacny** [comment]
Porównaj sobie działanie obu wersji na tej stronie:
https://polsatgo.pl/wideo/swiat-wedlug-kiepskich/5024025/autoplay
Na stronie jest chyba nextjs więc zwykle po zmienie urla wycina ikonę i trzeba odświeżyć, ale widać różnicę na korzyść tej nowszej wersji.

**Comment by zacny** [comment]
> Ten testowy skrypt miał niespójność z innymi serwisami, bo nie udało mi się tej ikonki kamery w inny sposób wyświetlić.
> 
> Pozostaje kwestia tego co zrobić ze skryptem na greasyfork. Może dodać aktualizację wyświetlającą powiadomienie o potrzebie instalacji z nowego źródła i pozbędziemy się tamtej stronki kompletnie?

Na to, nie mam na razie dobrego pomysłu.

**Comment by SebaK666** [comment]
Nie przeczę, korzystam właściwie tylko z polsatgo.pl i vod.tvp, kiedyś z player.pl, zanim "zakodowali". Mówię że zamiast robić oddzielne, zróbcie wspólny, możliwie najlepszy skrypt, wyłapując wzajemne błędy z obu skryptów.

**Comment by HerMajestyDrMona** [comment]
@SebaK666 O czym teraz piszesz? Skrypt jest jeden, synchronizuje (a przynajmniej synchronizował się) z greasyfork.
Ten na pastebin to szybka przeróbka wersji 7.2.4 bo płakali że nie działa po wprowadzeniu tego serwisu. Wolę nie ryzykować i nie zmieniać czegoś na githubie podczas nieobecności @zacny aby nie zepsuć totalnie. Kto szukał ten znalazł testową wersję.

**Comment by hubaiitv** [comment]
Najnowsza wersja skryptu nie dziala

**Comment by Womos** [comment]
Polsat Go Świat Według Kiepskich nie da się pobierać odcinków od 300 w dół te które były w SD jakości 576p ten sam problem co tutaj: https://greasyfork.org/en/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod/discussions/716

**Comment by Manticoraa** [comment]
Jak ominąć teraz na polsatgo.pl komunikat o wykryciu ublock origin? Miodowe lata.

**Comment by krzywish-crypto** [comment]
a czy jest coś co działa aktualnie na PolsatBoxGo?
