### ISSUE TITLE
polsatgo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [zacny/voddownloader#95]
mozna prosic o dodanie serwisu polsat go?

**Comment by HerMajestyDrMona** [comment]
https://github.com/zacny/voddownloader/issues/94#issuecomment-910877015

**Comment by username6669l** [comment]
nie mam pojecia o skryptach ale jakos uruchomilem na polsatboxgo. jesyneczka przy malpce tamper sie zaswiecila i kamerka do pobierania jest, moge sciagac 'chlopaki do wziecia'. dziekuje serdecznie :)
