### ISSUE TITLE
propozycja / polsatgo.pl

### ISSUE THREAD

**Issue by milo9559** [zacny/voddownloader#97]
Polsat odwalił jakąś manianę i ipli już nie ma. Podzielili ją na 2 strony polsatgo i polsatboxgo, niestety na obu wtyczka już nie działa
:( Dałoby radę odświeżyć wtyczkę aby była kompatybilna? Z góry dzięki!

**Comment by HerMajestyDrMona** [comment]
Proszę sprawdzać istniejące tematy przed zakładaniem nowych.
