### ISSUE TITLE
Nie dziala na vod.tvp.pl

### ISSUE THREAD

**Issue by Jacek63** [zacny/voddownloader#98]
Nie ma ikonki do pobierania na VOD.TVP.pl

**Comment by jaco7777** [comment]
1. Spróbuj przeładować stronę na której jest okno do wyświetlania filmu: klawisz F5 lub CTRL+F5.
2. Dodatkowo kursor myszki musi być na obszarze gdzie jest wyświetlany film.
3. Jeżeli nie pomoże, to może jakiś add block koliduje, spróbuj tymczasowo wyłaczyć.

Przed chwilą sprawdzałem i na stronie [https://vod.tvp.pl/video/generacja-algorytm,generacja-algorytm,53449566](https://vod.tvp.pl/video/generacja-algorytm,generacja-algorytm,53449566) mam ikonkę do pobierania.

**Comment by rafndev** [comment]
Potwierdzam - u mnie też działa.

**Comment by HerMajestyDrMona** [comment]
@Jacek63, spróbuj wersji z: https://github.com/zacny/voddownloader/issues/94#issuecomment-910877015
